//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AttachmentDtoAllOf { 
    /**
     * The id of the task attachment.
     */
    id?: string | null;
    /**
     * The name of the task attachment.
     */
    name?: string | null;
    /**
     * The description of the task attachment.
     */
    description?: string | null;
    /**
     * The id of the task to which the attachment belongs.
     */
    taskId?: string | null;
    /**
     * Indication of the type of content that this attachment refers to. Can be MIME type or any other indication.
     */
    type?: string | null;
    /**
     * The url to the remote content of the task attachment.
     */
    url?: string | null;
    /**
     * The time the variable was inserted. [Default format](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/) `yyyy-MM-dd\'T\'HH:mm:ss.SSSZ`.
     */
    createTime?: string | null;
    /**
     * The time after which the attachment should be removed by the History Cleanup job. [Default format](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/) `yyyy-MM-dd\'T\'HH:mm:ss.SSSZ`.
     */
    removalTime?: string | null;
    /**
     * The process instance id of the root process instance that initiated the process containing the task.
     */
    rootProcessInstanceId?: string | null;
}

