//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CaseDefinitionDto { 
    /**
     * The id of the case definition
     */
    id?: string | null;
    /**
     * The key of the case definition, i.e., the id of the CMMN 2.0 XML case definition.
     */
    key?: string | null;
    /**
     * The category of the case definition.
     */
    category?: string | null;
    /**
     * The name of the case definition.
     */
    name?: string | null;
    /**
     * The version of the case definition that the engine assigned to it.
     */
    version?: number | null;
    /**
     * The file name of the case definition.
     */
    resource?: string | null;
    /**
     * The deployment id of the case definition.
     */
    deploymentId?: string | null;
    /**
     * The tenant id of the case definition.
     */
    tenantId?: string | null;
    /**
     * History time to live value of the case definition. Is used within [History cleanup](https://docs.camunda.org/manual/7.16/user-guide/process-engine/history/#history-cleanup).
     */
    historyTimeToLive?: number | null;
}

