//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DecisionRequirementsDefinitionDto { 
    /**
     * The id of the decision requirements definition
     */
    id?: string | null;
    /**
     * The key of the decision requirements definition, i.e., the id of the DMN 1.0 XML decision definition.
     */
    key?: string | null;
    /**
     * The name of the decision requirements definition.
     */
    name?: string | null;
    /**
     * The category of the decision requirements definition.
     */
    category?: string | null;
    /**
     * The version of the decision requirements definition that the engine assigned to it.
     */
    version?: number | null;
    /**
     * The file name of the decision requirements definition.
     */
    resource?: string | null;
    /**
     * The deployment id of the decision requirements definition.
     */
    deploymentId?: string | null;
    /**
     * The tenant id of the decisionrequirements definition.
     */
    tenantId?: string | null;
}

