//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DecisionRequirementsDefinitionDto } from 'src/app/shared/services/camunda-api/model/decisionRequirementsDefinitionDto';
import { ProcessDefinitionDto } from 'src/app/shared/services/camunda-api/model/processDefinitionDto';
import { DecisionDefinitionDto } from 'src/app/shared/services/camunda-api/model/decisionDefinitionDto';
import { CaseDefinitionDto } from 'src/app/shared/services/camunda-api/model/caseDefinitionDto';


export interface DeploymentWithDefinitionsDtoAllOf { 
    /**
     * A JSON Object containing a property for each of the process definitions, which are successfully deployed with that deployment. The key is the process definition id, the value is a JSON Object corresponding to the process definition.
     */
    deployedProcessDefinitions?: { [key: string]: ProcessDefinitionDto; } | null;
    /**
     * A JSON Object containing a property for each of the decision definitions, which are successfully deployed with that deployment. The key is the decision definition id, the value is a JSON Object corresponding to the decision definition.
     */
    deployedDecisionDefinitions?: { [key: string]: DecisionDefinitionDto; } | null;
    /**
     * A JSON Object containing a property for each of the decision requirements definitions, which are successfully deployed with that deployment. The key is the decision requirements definition id, the value is a JSON Object corresponding to the decision requirements definition.
     */
    deployedDecisionRequirementsDefinitions?: { [key: string]: DecisionRequirementsDefinitionDto; } | null;
    /**
     * A JSON Object containing a property for each of the case definitions, which are successfully deployed with that deployment. The key is the case definition id, the value is a JSON Object corresponding to the case definition.
     */
    deployedCaseDefinitions?: { [key: string]: CaseDefinitionDto; } | null;
}

