//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExecutionQueryDtoSorting } from 'src/app/shared/services/camunda-api/model/executionQueryDtoSorting';
import { VariableQueryParameterDto } from 'src/app/shared/services/camunda-api/model/variableQueryParameterDto';


/**
 * A Execution instance query which defines a list of Execution instances
 */
export interface ExecutionQueryDto { 
    /**
     * Filter by the business key of the process instances the executions belong to.
     */
    businessKey?: string | null;
    /**
     * Filter by the process definition the executions run on.
     */
    processDefinitionId?: string | null;
    /**
     * Filter by the key of the process definition the executions run on.
     */
    processDefinitionKey?: string | null;
    /**
     * Filter by the id of the process instance the execution belongs to.
     */
    processInstanceId?: string | null;
    /**
     * Filter by the id of the activity the execution currently executes.
     */
    activityId?: string | null;
    /**
     * Select only those executions that expect a signal of the given name.
     */
    signalEventSubscriptionName?: string | null;
    /**
     * Select only those executions that expect a message of the given name.
     */
    messageEventSubscriptionName?: string | null;
    /**
     * Only include active executions. Value may only be `true`, as `false` is the default behavior.
     */
    active?: boolean | null;
    /**
     * Only include suspended executions. Value may only be `true`, as `false` is the default behavior.
     */
    suspended?: boolean | null;
    /**
     * Filter by the incident id.
     */
    incidentId?: string | null;
    /**
     * Filter by the incident type. See the [User Guide](/manual/develop/user-guide/process-engine/incidents/#incident-types) for a list of incident types.
     */
    incidentType?: string | null;
    /**
     * Filter by the incident message. Exact match.
     */
    incidentMessage?: string | null;
    /**
     * Filter by the incident message that the parameter is a substring of.
     */
    incidentMessageLike?: string | null;
    /**
     * Filter by a  list of tenant ids. An execution must have one of the given tenant ids.
     */
    tenantIdIn?: Array<string> | null;
    /**
     * An array to only include executions that have variables with certain values.  The array consists of objects with the three properties `name`, `operator` and `value`. `name (String)` is the variable name, `operator (String)` is the comparison operator to be used and `value` the variable value. `value` may be `String`, `Number` or `Boolean`.  Valid operator values are: `eq` - equal to; `neq` - not equal to; `gt` - greater than; `gteq` - greater than or equal to; `lt` - lower than; `lteq` - lower than or equal to; `like`.
     */
    variables?: Array<VariableQueryParameterDto> | null;
    /**
     * An array to only include executions that belong to a process instance with variables with certain values.  The array consists of objects with the three properties `name`, `operator` and `value`. `name (String)` is the variable name, `operator (String)` is the comparison operator to be used and `value` the variable value. `value` may be `String`, `Number` or `Boolean`.  Valid operator values are: `eq` - equal to; `neq` - not equal to.
     */
    processVariables?: Array<VariableQueryParameterDto> | null;
    /**
     * Match all variable names provided in `variables` and `processVariables` case- insensitively. If set to `true` **variableName** and **variablename** are treated as equal.
     */
    variableNamesIgnoreCase?: boolean | null;
    /**
     * Match all variable values provided in `variables` and `processVariables` case- insensitively. If set to `true` **variableValue** and **variablevalue** are treated as equal.
     */
    variableValuesIgnoreCase?: boolean | null;
    /**
     * An array of criteria to sort the result by. Each element of the array is                        an object that specifies one ordering. The position in the array                        identifies the rank of an ordering, i.e., whether it is primary, secondary,                        etc. Has no effect for the `/count` endpoint
     */
    sorting?: Array<ExecutionQueryDtoSorting> | null;
}

