//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExecutionDto { 
    /**
     * The id of the Execution.
     */
    id?: string | null;
    /**
     * The id of the root of the execution tree representing the process instance.
     */
    processInstanceId?: string | null;
    /**
     * Indicates if the execution is ended.
     */
    ended?: boolean | null;
    /**
     * The id of the tenant this execution belongs to. Can be `null` if the execution belongs to no single tenant.
     */
    tenantId?: string | null;
}

