//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HistoricTaskInstanceQueryDtoSorting { 
    /**
     * Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter.
     */
    sortBy?: HistoricTaskInstanceQueryDtoSorting.SortByEnum | null;
    /**
     * Sort the results in a given order. Values may be `asc` for ascending order or `desc` for descending order. Must be used in conjunction with the sortBy parameter.
     */
    sortOrder?: HistoricTaskInstanceQueryDtoSorting.SortOrderEnum | null;
}
export namespace HistoricTaskInstanceQueryDtoSorting {
    export type SortByEnum = 'taskId' | 'activityInstanceId' | 'processDefinitionId' | 'processInstanceId' | 'executionId' | 'duration' | 'endTime' | 'startTime' | 'taskName' | 'taskDescription' | 'assignee' | 'owner' | 'dueDate' | 'followUpDate' | 'deleteReason' | 'taskDefinitionKey' | 'priority' | 'caseDefinitionId' | 'caseInstanceId' | 'caseExecutionId' | 'tenantId';
    export const SortByEnum = {
        TaskId: 'taskId' as SortByEnum,
        ActivityInstanceId: 'activityInstanceId' as SortByEnum,
        ProcessDefinitionId: 'processDefinitionId' as SortByEnum,
        ProcessInstanceId: 'processInstanceId' as SortByEnum,
        ExecutionId: 'executionId' as SortByEnum,
        Duration: 'duration' as SortByEnum,
        EndTime: 'endTime' as SortByEnum,
        StartTime: 'startTime' as SortByEnum,
        TaskName: 'taskName' as SortByEnum,
        TaskDescription: 'taskDescription' as SortByEnum,
        Assignee: 'assignee' as SortByEnum,
        Owner: 'owner' as SortByEnum,
        DueDate: 'dueDate' as SortByEnum,
        FollowUpDate: 'followUpDate' as SortByEnum,
        DeleteReason: 'deleteReason' as SortByEnum,
        TaskDefinitionKey: 'taskDefinitionKey' as SortByEnum,
        Priority: 'priority' as SortByEnum,
        CaseDefinitionId: 'caseDefinitionId' as SortByEnum,
        CaseInstanceId: 'caseInstanceId' as SortByEnum,
        CaseExecutionId: 'caseExecutionId' as SortByEnum,
        TenantId: 'tenantId' as SortByEnum
    };
    export type SortOrderEnum = 'asc' | 'desc';
    export const SortOrderEnum = {
        Asc: 'asc' as SortOrderEnum,
        Desc: 'desc' as SortOrderEnum
    };
}


