//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HistoricBatchQueryDtoSorting } from 'src/app/shared/services/camunda-api/model/historicBatchQueryDtoSorting';


/**
 * Query for the historic batches to set the removal time for.
 */
export interface HistoricBatchQueryDto { 
    /**
     * Filter by batch id.
     */
    batchId?: string | null;
    /**
     * Filter by batch type. See the [User Guide](https://docs.camunda.org/manual/7.16/user-guide/process-engine/batch/#creating-a-batch) for more information about batch types.
     */
    type?: string | null;
    /**
     *  Filter completed or not completed batches. If the value is `true`, only completed batches, i.e., end time is set, are returned. Otherwise, if the value is `false`, only running batches, i.e., end time is null, are returned.
     */
    completed?: boolean | null;
    /**
     * Filter by a comma-separated list of tenant ids. A batch matches if it has one of the given tenant ids.
     */
    tenantIdIn?: Array<string> | null;
    /**
     * Only include batches which belong to no tenant. Value can effectively only be `true`, as `false` is the default behavior.
     */
    withoutTenantId?: boolean | null;
    /**
     * An array of criteria to sort the result by. Each element of the array is                        an object that specifies one ordering. The position in the array                        identifies the rank of an ordering, i.e., whether it is primary, secondary,                        etc. Has no effect for the `/count` endpoint
     */
    sorting?: Array<HistoricBatchQueryDtoSorting> | null;
}

