//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HistoricDetailQueryDtoSorting } from 'src/app/shared/services/camunda-api/model/historicDetailQueryDtoSorting';


/**
 * A historic detail query which defines a group of historic details.
 */
export interface HistoricDetailQueryDto { 
    /**
     * Filter by process instance id.
     */
    processInstanceId?: string | null;
    /**
     * Only include historic details which belong to one of the passed  process instance ids.
     */
    processInstanceIdIn?: Array<string> | null;
    /**
     * Filter by execution id.
     */
    executionId?: string | null;
    /**
     * Filter by task id.
     */
    taskId?: string | null;
    /**
     * Filter by activity instance id.
     */
    activityInstanceId?: string | null;
    /**
     * Filter by case instance id.
     */
    caseInstanceId?: string | null;
    /**
     * Filter by case execution id.
     */
    caseExecutionId?: string | null;
    /**
     * Filter by variable instance id.
     */
    variableInstanceId?: string | null;
    /**
     * Only include historic details where the variable updates belong to one of the passed  list of variable types. A list of all supported variable types can be found [here](https://docs.camunda.org/manual/7.16/user-guide/process-engine/variables/#supported-variable-values). **Note:** All non-primitive variables are associated with the type `serializable`.
     */
    variableTypeIn?: Array<string> | null;
    /**
     * Filter by a  list of tenant ids.
     */
    tenantIdIn?: Array<string> | null;
    /**
     * Only include historic details that belong to no tenant. Value may only be `true`, as `false` is the default behavior.
     */
    withoutTenantId?: boolean | null;
    /**
     * Filter by a user operation id.
     */
    userOperationId?: string | null;
    /**
     * Only include `HistoricFormFields`. Value may only be `true`, as `false` is the default behavior.
     */
    formFields?: boolean | null;
    /**
     * Only include `HistoricVariableUpdates`. Value may only be `true`, as `false` is the default behavior.
     */
    variableUpdates?: boolean | null;
    /**
     * Excludes all task-related `HistoricDetails`, so only items which have no task id set will be selected. When this parameter is used together with `taskId`, this call is ignored and task details are not excluded. Value may only be `true`, as `false` is the default behavior.
     */
    excludeTaskDetails?: boolean | null;
    /**
     * Restrict to historic variable updates that contain only initial variable values. Value may only be `true`, as `false` is the default behavior.
     */
    initial?: boolean | null;
    /**
     * Restrict to historic details that occured before the given date (including the date). Default [format](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/) `yyyy-MM-dd\'T\'HH:mm:ss.SSSZ`, e.g., 2013-01-23T14:42:45.000+0200.
     */
    occurredBefore?: string | null;
    /**
     * Restrict to historic details that occured after the given date (including the date). Default [format](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/) `yyyy-MM-dd\'T\'HH:mm:ss.SSSZ`, e.g., 2013-01-23T14:42:45.000+0200.
     */
    occurredAfter?: string | null;
    /**
     * A JSON array of criteria to sort the result by. Each element of the array is                     a JSON object that specifies one ordering. The position in the array                     identifies the rank of an ordering, i.e., whether it is primary, secondary,                     etc. Does not have an effect for the `count` endpoint.
     */
    sorting?: Array<HistoricDetailQueryDtoSorting> | null;
}

