//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JobDto { 
    /**
     * The id of the job.
     */
    id?: string | null;
    /**
     * The id of the associated job definition.
     */
    jobDefinitionId?: string | null;
    /**
     * The date on which this job is supposed to be processed.
     */
    dueDate?: string | null;
    /**
     * The id of the process instance which execution created the job.
     */
    processInstanceId?: string | null;
    /**
     * The specific execution id on which the job was created.
     */
    executionId?: string | null;
    /**
     * The id of the process definition which this job belongs to.
     */
    processDefinitionId?: string | null;
    /**
     * The key of the process definition which this job belongs to.
     */
    processDefinitionKey?: string | null;
    /**
     * The number of retries this job has left.
     */
    retries?: number | null;
    /**
     * The message of the exception that occurred, the last time the job was executed. Is null when no exception occurred.
     */
    exceptionMessage?: string | null;
    /**
     * The id of the activity on which the last exception occurred, the last time the job was executed. Is null when no exception occurred.
     */
    failedActivityId?: string | null;
    /**
     * A flag indicating whether the job is suspended or not.
     */
    suspended?: boolean | null;
    /**
     * The job\'s priority for execution.
     */
    priority?: number | null;
    /**
     * The id of the tenant which this job belongs to.
     */
    tenantId?: string | null;
    /**
     * The date on which this job has been created.
     */
    createTime?: string | null;
}

