//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VariableValueDto } from 'src/app/shared/services/camunda-api/model/variableValueDto';


export interface LockedExternalTaskDto { 
    /**
     * The id of the activity that this external task belongs to.
     */
    activityId?: string | null;
    /**
     * The id of the activity instance that the external task belongs to.
     */
    activityInstanceId?: string | null;
    /**
     * The full error message submitted with the latest reported failure executing this task;`null` if no failure was reported previously or if no error message was submitted
     */
    errorMessage?: string | null;
    /**
     * The error details submitted with the latest reported failure executing this task.`null` if no failure was reported previously or if no error details was submitted
     */
    errorDetails?: string | null;
    /**
     * The id of the execution that the external task belongs to.
     */
    executionId?: string | null;
    /**
     * The id of the external task.
     */
    id?: string | null;
    /**
     * The date that the task\'s most recent lock expires or has expired.
     */
    lockExpirationTime?: string | null;
    /**
     * The id of the process definition the external task is defined in.
     */
    processDefinitionId?: string | null;
    /**
     * The key of the process definition the external task is defined in.
     */
    processDefinitionKey?: string | null;
    /**
     * The version tag of the process definition the external task is defined in.
     */
    processDefinitionVersionTag?: string | null;
    /**
     * The id of the process instance the external task belongs to.
     */
    processInstanceId?: string | null;
    /**
     * The id of the tenant the external task belongs to.
     */
    tenantId?: string | null;
    /**
     * The number of retries the task currently has left.
     */
    retries?: number | null;
    /**
     * Whether the process instance the external task belongs to is suspended.
     */
    suspended?: boolean | null;
    /**
     * The id of the worker that posesses or posessed the most recent lock.
     */
    workerId?: string | null;
    /**
     * The priority of the external task.
     */
    priority?: number | null;
    /**
     * The topic name of the external task.
     */
    topicName?: string | null;
    /**
     * The business key of the process instance the external task belongs to.
     */
    businessKey?: string | null;
    /**
     * A JSON object containing a property for each of the requested variables. The key is the variable name, the value is a JSON object of serialized variable values with the following properties:
     */
    variables?: { [key: string]: VariableValueDto; } | null;
}

