//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IncidentStatisticsResultDto } from 'src/app/shared/services/camunda-api/model/incidentStatisticsResultDto';
import { ProcessDefinitionDto } from 'src/app/shared/services/camunda-api/model/processDefinitionDto';


export interface ProcessDefinitionStatisticsResultDto { 
    /**
     * The id of the process definition the results are aggregated for.
     */
    id?: string | null;
    /**
     * The total number of running process instances of this process definition.
     */
    instances?: number;
    /**
     * The total number of failed jobs for the running instances. **Note**: Will be `0` (not `null`), if failed jobs were excluded.
     */
    failedJobs?: number;
    /**
     * Each item in the resulting array is an object which contains `incidentType` and `incidentCount`. **Note**: Will be an empty array, if `incidents` or `incidentsForType` were excluded. Furthermore, the array will be also empty if no incidents were found.
     */
    incidents?: Array<IncidentStatisticsResultDto> | null;
    definition?: ProcessDefinitionDto;
}

