//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SortTaskQueryParametersDto } from 'src/app/shared/services/camunda-api/model/sortTaskQueryParametersDto';


export interface TaskQueryDtoSorting { 
    /**
     * Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter.
     */
    sortBy?: TaskQueryDtoSorting.SortByEnum | null;
    /**
     * Sort the results in a given order. Values may be `asc` for ascending order or `desc` for descending order. Must be used in conjunction with the sortBy parameter.
     */
    sortOrder?: TaskQueryDtoSorting.SortOrderEnum | null;
    parameters?: SortTaskQueryParametersDto;
}
export namespace TaskQueryDtoSorting {
    export type SortByEnum = 'instanceId' | 'caseInstanceId' | 'dueDate' | 'executionId' | 'caseExecutionId' | 'assignee' | 'created' | 'description' | 'id' | 'name' | 'nameCaseInsensitive' | 'priority' | 'processVariable' | 'executionVariable' | 'taskVariable' | 'caseExecutionVariable' | 'caseInstanceVariable';
    export const SortByEnum = {
        InstanceId: 'instanceId' as SortByEnum,
        CaseInstanceId: 'caseInstanceId' as SortByEnum,
        DueDate: 'dueDate' as SortByEnum,
        ExecutionId: 'executionId' as SortByEnum,
        CaseExecutionId: 'caseExecutionId' as SortByEnum,
        Assignee: 'assignee' as SortByEnum,
        Created: 'created' as SortByEnum,
        Description: 'description' as SortByEnum,
        Id: 'id' as SortByEnum,
        Name: 'name' as SortByEnum,
        NameCaseInsensitive: 'nameCaseInsensitive' as SortByEnum,
        Priority: 'priority' as SortByEnum,
        ProcessVariable: 'processVariable' as SortByEnum,
        ExecutionVariable: 'executionVariable' as SortByEnum,
        TaskVariable: 'taskVariable' as SortByEnum,
        CaseExecutionVariable: 'caseExecutionVariable' as SortByEnum,
        CaseInstanceVariable: 'caseInstanceVariable' as SortByEnum
    };
    export type SortOrderEnum = 'asc' | 'desc';
    export const SortOrderEnum = {
        Asc: 'asc' as SortOrderEnum,
        Desc: 'desc' as SortOrderEnum
    };
}


