//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivityInstanceIncidentDto } from 'src/app/shared/services/camunda-api/model/activityInstanceIncidentDto';


/**
 * A JSON object corresponding to the Activity Instance tree of the given process instance.
 */
export interface TransitionInstanceDto { 
    /**
     * The id of the transition instance.
     */
    id?: string | null;
    /**
     * The id of the parent activity instance, for example a sub process instance.
     */
    parentActivityInstanceId?: string | null;
    /**
     * The id of the activity that this instance enters (asyncBefore job) or leaves (asyncAfter job)
     */
    activityId?: string | null;
    /**
     * The name of the activity that this instance enters (asyncBefore job) or leaves (asyncAfter job)
     */
    activityName?: string | null;
    /**
     * The type of the activity that this instance enters (asyncBefore job) or leaves (asyncAfter job)
     */
    activityType?: string | null;
    /**
     * The id of the process instance this instance is part of.
     */
    processInstanceId?: string | null;
    /**
     * The id of the process definition.
     */
    processDefinitionId?: string | null;
    /**
     * The execution id.
     */
    executionId?: string | null;
    /**
     * A list of incident ids.
     */
    incidentIds?: Array<string> | null;
    /**
     * A list of JSON objects containing incident specific properties: * `id`: the id of the incident * `activityId`: the activity id in which the incident occurred
     */
    incidents?: Array<ActivityInstanceIncidentDto> | null;
}

