//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserOperationLogEntryDto { 
    /**
     * The unique identifier of this log entry.
     */
    id?: string | null;
    /**
     * The user who performed this operation.
     */
    userId?: string | null;
    /**
     * Timestamp of this operation.
     */
    timestamp?: string | null;
    /**
     * The unique identifier of this operation. A composite operation that changes multiple properties has a common `operationId`.
     */
    operationId?: string | null;
    /**
     * The type of this operation, e.g., `Assign`, `Claim` and so on.
     */
    operationType?: string | null;
    /**
     * The type of the entity on which this operation was executed, e.g., `Task` or `Attachment`.
     */
    entityType?: string | null;
    /**
     * The name of the category this operation was associated with, e.g., `TaskWorker` or `Admin`.
     */
    category?: string | null;
    /**
     * An arbitrary annotation set by a user for auditing reasons.
     */
    annotation?: string | null;
    /**
     * The property changed by this operation.
     */
    property?: string | null;
    /**
     * The original value of the changed property.
     */
    orgValue?: string | null;
    /**
     * The new value of the changed property.
     */
    newValue?: string | null;
    /**
     * If not `null`, the operation is restricted to entities in relation to this deployment.
     */
    deploymentId?: string | null;
    /**
     * If not `null`, the operation is restricted to entities in relation to this process definition.
     */
    processDefinitionId?: string | null;
    /**
     * If not `null`, the operation is restricted to entities in relation to process definitions with this key.
     */
    processDefinitionKey?: string | null;
    /**
     * If not `null`, the operation is restricted to entities in relation to this process instance.
     */
    processInstanceId?: string | null;
    /**
     * If not `null`, the operation is restricted to entities in relation to this execution.
     */
    executionId?: string | null;
    /**
     * If not `null`, the operation is restricted to entities in relation to this case definition.
     */
    caseDefinitionId?: string | null;
    /**
     * If not `null`, the operation is restricted to entities in relation to this case instance.
     */
    caseInstanceId?: string | null;
    /**
     * If not `null`, the operation is restricted to entities in relation to this case execution.
     */
    caseExecutionId?: string | null;
    /**
     * If not `null`, the operation is restricted to entities in relation to this task.
     */
    taskId?: string | null;
    /**
     * If not `null`, the operation is restricted to entities in relation to this external task.
     */
    externalTaskId?: string | null;
    /**
     * If not `null`, the operation is restricted to entities in relation to this batch.
     */
    batchId?: string | null;
    /**
     * If not `null`, the operation is restricted to entities in relation to this job.
     */
    jobId?: string | null;
    /**
     * If not `null`, the operation is restricted to entities in relation to this job definition.
     */
    jobDefinitionId?: string | null;
    /**
     * The time after which the entry should be removed by the History Cleanup job. [Default format](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/) `yyyy-MM-dd\'T\'HH:mm:ss.SSSZ`.
     */
    removalTime?: string | null;
    /**
     * The process instance id of the root process instance that initiated the process containing this entry.
     */
    rootProcessInstanceId?: string | null;
}

