//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent, HttpParameterCodec, HttpContext } from '@angular/common/http';
import { CustomHttpParameterCodec } from 'src/app/shared/services/camunda-api/encoder';
import { Observable } from 'rxjs';

// @ts-ignore
import { BatchDto } from 'src/app/shared/services/camunda-api/model/batchDto';
// @ts-ignore
import { CountResultDto } from 'src/app/shared/services/camunda-api/model/countResultDto';
// @ts-ignore
import { DeleteHistoricProcessInstancesDto } from 'src/app/shared/services/camunda-api/model/deleteHistoricProcessInstancesDto';
// @ts-ignore
import { DurationReportResultDto } from 'src/app/shared/services/camunda-api/model/durationReportResultDto';
// @ts-ignore
import { ExceptionDto } from 'src/app/shared/services/camunda-api/model/exceptionDto';
// @ts-ignore
import { HistoricProcessInstanceDto } from 'src/app/shared/services/camunda-api/model/historicProcessInstanceDto';
// @ts-ignore
import { HistoricProcessInstanceQueryDto } from 'src/app/shared/services/camunda-api/model/historicProcessInstanceQueryDto';
// @ts-ignore
import { SetRemovalTimeToHistoricProcessInstancesDto } from 'src/app/shared/services/camunda-api/model/setRemovalTimeToHistoricProcessInstancesDto';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from 'src/app/shared/services/camunda-api/variables';
import { Configuration } from 'src/app/shared/services/camunda-api/configuration';

@Injectable({
  providedIn: 'root',
})
export class HistoricProcessInstanceService {
  protected basePath = 'http://localhost:8080/engine-rest';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  public encoder: HttpParameterCodec;

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration
  ) {
    if (configuration) {
      this.configuration = configuration;
    }
    if (typeof this.configuration.basePath !== 'string') {
      if (typeof basePath !== 'string') {
        basePath = this.basePath;
      }
      this.configuration.basePath = basePath;
    }
    this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
  }

  private addToHttpParams(
    httpParams: HttpParams,
    value: any,
    key?: string
  ): HttpParams {
    if (typeof value === 'object' && value instanceof Date === false) {
      httpParams = this.addToHttpParamsRecursive(httpParams, value);
    } else {
      httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
    }
    return httpParams;
  }

  private addToHttpParamsRecursive(
    httpParams: HttpParams,
    value?: any,
    key?: string
  ): HttpParams {
    if (value == null) {
      return httpParams;
    }

    if (typeof value === 'object') {
      if (Array.isArray(value)) {
        (value as any[]).forEach(
          (elem) =>
            (httpParams = this.addToHttpParamsRecursive(httpParams, elem, key))
        );
      } else if (value instanceof Date) {
        if (key != null) {
          httpParams = httpParams.append(
            key,
            (value as Date).toISOString().substr(0, 10)
          );
        } else {
          throw Error('key may not be null if value is Date');
        }
      } else {
        Object.keys(value).forEach(
          (k) =>
            (httpParams = this.addToHttpParamsRecursive(
              httpParams,
              value[k],
              key != null ? `${key}.${k}` : k
            ))
        );
      }
    } else if (key != null) {
      httpParams = httpParams.append(key, value);
    } else {
      throw Error('key may not be null if value is not object or array');
    }
    return httpParams;
  }

  /**
   * Delete
   * Deletes a process instance from the history by id.
   * @param id The id of the historic process instance to be deleted.
   * @param failIfNotExists If set to &#x60;false&#x60;, the request will still be successful if the process id is not found.
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteHistoricProcessInstance(
    id: string,
    failIfNotExists?: boolean,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<any>;
  public deleteHistoricProcessInstance(
    id: string,
    failIfNotExists?: boolean,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpResponse<any>>;
  public deleteHistoricProcessInstance(
    id: string,
    failIfNotExists?: boolean,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpEvent<any>>;
  public deleteHistoricProcessInstance(
    id: string,
    failIfNotExists?: boolean,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        'Required parameter id was null or undefined when calling deleteHistoricProcessInstance.'
      );
    }

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    if (failIfNotExists !== undefined && failIfNotExists !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>failIfNotExists,
        'failIfNotExists'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    let localVarHttpHeaderAcceptSelected: string | undefined =
      options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected =
        this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Accept',
        localVarHttpHeaderAcceptSelected
      );
    }

    let localVarHttpContext: HttpContext | undefined =
      options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (
        this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
      ) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    return this.httpClient.delete<any>(
      `${
        this.configuration.basePath
      }/history/process-instance/${encodeURIComponent(String(id))}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Delete Async (POST)
   * Delete multiple historic process instances asynchronously (batch). At least &#x60;historicProcessInstanceIds&#x60; or &#x60;historicProcessInstanceQuery&#x60; has to be provided. If both are provided then all instances matching query criterion and instances from the list will be deleted.
   * @param deleteHistoricProcessInstancesDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteHistoricProcessInstancesAsync(
    deleteHistoricProcessInstancesDto?: DeleteHistoricProcessInstancesDto,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<BatchDto>;
  public deleteHistoricProcessInstancesAsync(
    deleteHistoricProcessInstancesDto?: DeleteHistoricProcessInstancesDto,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpResponse<BatchDto>>;
  public deleteHistoricProcessInstancesAsync(
    deleteHistoricProcessInstancesDto?: DeleteHistoricProcessInstancesDto,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpEvent<BatchDto>>;
  public deleteHistoricProcessInstancesAsync(
    deleteHistoricProcessInstancesDto?: DeleteHistoricProcessInstancesDto,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<any> {
    let localVarHeaders = this.defaultHeaders;

    let localVarHttpHeaderAcceptSelected: string | undefined =
      options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected =
        this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Accept',
        localVarHttpHeaderAcceptSelected
      );
    }

    let localVarHttpContext: HttpContext | undefined =
      options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined =
      this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Content-Type',
        httpContentTypeSelected
      );
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (
        this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
      ) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    return this.httpClient.post<BatchDto>(
      `${this.configuration.basePath}/history/process-instance/delete`,
      deleteHistoricProcessInstancesDto,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Delete Variable Instances
   * Deletes all variables of a process instance from the history by id.
   * @param id The id of the process instance for which all historic variables are to be deleted.
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteHistoricVariableInstancesOfHistoricProcessInstance(
    id: string,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<any>;
  public deleteHistoricVariableInstancesOfHistoricProcessInstance(
    id: string,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpResponse<any>>;
  public deleteHistoricVariableInstancesOfHistoricProcessInstance(
    id: string,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpEvent<any>>;
  public deleteHistoricVariableInstancesOfHistoricProcessInstance(
    id: string,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        'Required parameter id was null or undefined when calling deleteHistoricVariableInstancesOfHistoricProcessInstance.'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    let localVarHttpHeaderAcceptSelected: string | undefined =
      options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected =
        this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Accept',
        localVarHttpHeaderAcceptSelected
      );
    }

    let localVarHttpContext: HttpContext | undefined =
      options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (
        this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
      ) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    return this.httpClient.delete<any>(
      `${
        this.configuration.basePath
      }/history/process-instance/${encodeURIComponent(
        String(id)
      )}/variable-instances`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Get
   * Retrieves a historic process instance by id, according to the &#x60;HistoricProcessInstance&#x60; interface in the engine.
   * @param id The id of the historic process instance to be retrieved.
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getHistoricProcessInstance(
    id: string,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HistoricProcessInstanceDto>;
  public getHistoricProcessInstance(
    id: string,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpResponse<HistoricProcessInstanceDto>>;
  public getHistoricProcessInstance(
    id: string,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpEvent<HistoricProcessInstanceDto>>;
  public getHistoricProcessInstance(
    id: string,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        'Required parameter id was null or undefined when calling getHistoricProcessInstance.'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    let localVarHttpHeaderAcceptSelected: string | undefined =
      options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected =
        this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Accept',
        localVarHttpHeaderAcceptSelected
      );
    }

    let localVarHttpContext: HttpContext | undefined =
      options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (
        this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
      ) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    return this.httpClient.get<HistoricProcessInstanceDto>(
      `${
        this.configuration.basePath
      }/history/process-instance/${encodeURIComponent(String(id))}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Get Duration Report
   * Retrieves a report about the duration of completed process instances, grouped by a period. These reports include the maximum, minimum and average duration of all completed process instances which were started in a given period.  **Note:** This only includes historic data.
   * @param reportType **Mandatory.** Specifies the type of the report to retrieve. To retrieve a report about the duration of process instances, the value must be set to &#x60;duration&#x60;.
   * @param periodUnit **Mandatory.** Specifies the granularity of the report. Valid values are &#x60;month&#x60; and &#x60;quarter&#x60;.
   * @param processDefinitionIdIn Filter by process definition ids. Must be a comma-separated list of process definition ids.
   * @param processDefinitionKeyIn Filter by process definition keys. Must be a comma-separated list of process definition keys.
   * @param startedBefore Restrict to instances that were started before the given date. By [default](), the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., &#x60;2016-01-23T14:42:45.000+0200&#x60;.
   * @param startedAfter Restrict to instances that were started after the given date. By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/), the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., &#x60;2016-01-23T14:42:45.000+0200&#x60;.
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getHistoricProcessInstanceDurationReport(
    reportType: string,
    periodUnit: 'month' | 'quarter',
    processDefinitionIdIn?: string,
    processDefinitionKeyIn?: string,
    startedBefore?: string,
    startedAfter?: string,
    observe?: 'body',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json' | 'application/csv' | 'text/csv';
      context?: HttpContext;
    }
  ): Observable<Array<DurationReportResultDto>>;
  public getHistoricProcessInstanceDurationReport(
    reportType: string,
    periodUnit: 'month' | 'quarter',
    processDefinitionIdIn?: string,
    processDefinitionKeyIn?: string,
    startedBefore?: string,
    startedAfter?: string,
    observe?: 'response',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json' | 'application/csv' | 'text/csv';
      context?: HttpContext;
    }
  ): Observable<HttpResponse<Array<DurationReportResultDto>>>;
  public getHistoricProcessInstanceDurationReport(
    reportType: string,
    periodUnit: 'month' | 'quarter',
    processDefinitionIdIn?: string,
    processDefinitionKeyIn?: string,
    startedBefore?: string,
    startedAfter?: string,
    observe?: 'events',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json' | 'application/csv' | 'text/csv';
      context?: HttpContext;
    }
  ): Observable<HttpEvent<Array<DurationReportResultDto>>>;
  public getHistoricProcessInstanceDurationReport(
    reportType: string,
    periodUnit: 'month' | 'quarter',
    processDefinitionIdIn?: string,
    processDefinitionKeyIn?: string,
    startedBefore?: string,
    startedAfter?: string,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: {
      httpHeaderAccept?: 'application/json' | 'application/csv' | 'text/csv';
      context?: HttpContext;
    }
  ): Observable<any> {
    if (reportType === null || reportType === undefined) {
      throw new Error(
        'Required parameter reportType was null or undefined when calling getHistoricProcessInstanceDurationReport.'
      );
    }
    if (periodUnit === null || periodUnit === undefined) {
      throw new Error(
        'Required parameter periodUnit was null or undefined when calling getHistoricProcessInstanceDurationReport.'
      );
    }

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    if (reportType !== undefined && reportType !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>reportType,
        'reportType'
      );
    }
    if (periodUnit !== undefined && periodUnit !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>periodUnit,
        'periodUnit'
      );
    }
    if (processDefinitionIdIn !== undefined && processDefinitionIdIn !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processDefinitionIdIn,
        'processDefinitionIdIn'
      );
    }
    if (
      processDefinitionKeyIn !== undefined &&
      processDefinitionKeyIn !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processDefinitionKeyIn,
        'processDefinitionKeyIn'
      );
    }
    if (startedBefore !== undefined && startedBefore !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>startedBefore,
        'startedBefore'
      );
    }
    if (startedAfter !== undefined && startedAfter !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>startedAfter,
        'startedAfter'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    let localVarHttpHeaderAcceptSelected: string | undefined =
      options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = [
        'application/json',
        'application/csv',
        'text/csv',
      ];
      localVarHttpHeaderAcceptSelected =
        this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Accept',
        localVarHttpHeaderAcceptSelected
      );
    }

    let localVarHttpContext: HttpContext | undefined =
      options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (
        this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
      ) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    return this.httpClient.get<Array<DurationReportResultDto>>(
      `${this.configuration.basePath}/history/process-instance/report`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Get List
   * Queries for historic process instances that fulfill the given parameters. The size of the result set can be retrieved by using the [Get Process Instance Count](https://docs.camunda.org/manual/7.16/reference/rest/history/process-instance/get-process-instance-query-count/) method.
   * @param sortBy Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter.
   * @param sortOrder Sort the results in a given order. Values may be asc for ascending order or desc for descending order. Must be used in conjunction with the sortBy parameter.
   * @param firstResult Pagination of results. Specifies the index of the first result to return.
   * @param maxResults Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left.
   * @param processInstanceId Filter by process instance id.
   * @param processInstanceIds Filter by process instance ids. Filter by a comma-separated list of &#x60;Strings&#x60;.
   * @param processDefinitionId Filter by the process definition the instances run on.
   * @param processDefinitionKey Filter by the key of the process definition the instances run on.
   * @param processDefinitionKeyIn Filter by a list of process definition keys. A process instance must have one of the given process definition keys. Filter by a comma-separated list of &#x60;Strings&#x60;.
   * @param processDefinitionName Filter by the name of the process definition the instances run on.
   * @param processDefinitionNameLike Filter by process definition names that the parameter is a substring of.
   * @param processDefinitionKeyNotIn Exclude instances that belong to a set of process definitions. Filter by a comma-separated list of &#x60;Strings&#x60;.
   * @param processInstanceBusinessKey Filter by process instance business key.
   * @param processInstanceBusinessKeyLike Filter by process instance business key that the parameter is a substring of.
   * @param rootProcessInstances Restrict the query to all process instances that are top level process instances.
   * @param finished Only include finished process instances. This flag includes all process instances that are completed or terminated. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
   * @param unfinished Only include unfinished process instances. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
   * @param withIncidents Only include process instances which have an incident. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
   * @param withRootIncidents Only include process instances which have a root incident. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
   * @param incidentType Filter by the incident type. See the [User Guide](https://docs.camunda.org/manual/7.16/user-guide/process-engine/incidents/#incident-types) for a list of incident types.
   * @param incidentStatus Only include process instances which have an incident in status either open or resolved. To get all process instances, use the query parameter withIncidents.
   * @param incidentMessage Filter by the incident message. Exact match.
   * @param incidentMessageLike Filter by the incident message that the parameter is a substring of.
   * @param startedBefore Restrict to instances that were started before the given date. By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/), the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
   * @param startedAfter Restrict to instances that were started after the given date. By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/), the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
   * @param finishedBefore Restrict to instances that were finished before the given date. By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/), the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
   * @param finishedAfter Restrict to instances that were finished after the given date. By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/), the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
   * @param executedActivityAfter Restrict to instances that executed an activity after the given date (inclusive). By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/), the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
   * @param executedActivityBefore Restrict to instances that executed an activity before the given date (inclusive). By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/), the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
   * @param executedJobAfter Restrict to instances that executed an job after the given date (inclusive). By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/), the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
   * @param executedJobBefore Restrict to instances that executed an job before the given date (inclusive). By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/), the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
   * @param startedBy Only include process instances that were started by the given user.
   * @param superProcessInstanceId Restrict query to all process instances that are sub process instances of the given process instance. Takes a process instance id.
   * @param subProcessInstanceId Restrict query to one process instance that has a sub process instance with the given id.
   * @param superCaseInstanceId Restrict query to all process instances that are sub process instances of the given case instance. Takes a case instance id.
   * @param subCaseInstanceId Restrict query to one process instance that has a sub case instance with the given id.
   * @param caseInstanceId Restrict query to all process instances that are sub process instances of the given case instance. Takes a case instance id.
   * @param tenantIdIn Filter by a list of tenant ids. A process instance must have one of the given tenant ids. Filter by a comma-separated list of &#x60;Strings&#x60;
   * @param withoutTenantId Only include historic process instances which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
   * @param executedActivityIdIn Restrict to instances that executed an activity with one of given ids. Filter by a comma-separated list of &#x60;Strings&#x60;
   * @param activeActivityIdIn Restrict to instances that have an active activity with one of given ids. Filter by a comma-separated list of &#x60;Strings&#x60;
   * @param active Restrict to instances that are active.
   * @param suspended Restrict to instances that are suspended.
   * @param completed Restrict to instances that are completed.
   * @param externallyTerminated Restrict to instances that are externallyTerminated.
   * @param internallyTerminated Restrict to instances that are internallyTerminated.
   * @param variables Only include process instances that have/had variables with certain values. Variable filtering expressions are comma-separated and are structured as follows: A valid parameter value has the form &#x60;key_operator_value&#x60;. &#x60;key&#x60; is the variable name, &#x60;operator&#x60; is the comparison operator to be used and &#x60;value&#x60; the variable value.  **Note:** Values are always treated as String objects on server side.  Valid operator values are: &#x60;eq&#x60; - equal to; &#x60;neq&#x60; - not equal to; &#x60;gt&#x60; - greater than; &#x60;gteq&#x60; - greater than or equal to; &#x60;lt&#x60; - lower than; &#x60;lteq&#x60; - lower than or equal to; &#x60;like&#x60;.  Key and value may not contain underscore or comma characters.
   * @param variableNamesIgnoreCase Match all variable names provided in variables case-insensitively. If set to &#x60;true&#x60; variableName and variablename are treated as equal.
   * @param variableValuesIgnoreCase Match all variable values provided in variables case-insensitively. If set to &#x60;true&#x60; variableValue and variablevalue are treated as equal.
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getHistoricProcessInstances(
    sortBy?:
      | 'instanceId'
      | 'definitionId'
      | 'definitionKey'
      | 'definitionName'
      | 'definitionVersion'
      | 'businessKey'
      | 'startTime'
      | 'endTime'
      | 'duration'
      | 'tenantId',
    sortOrder?: 'asc' | 'desc',
    firstResult?: number,
    maxResults?: number,
    processInstanceId?: string,
    processInstanceIds?: string,
    processDefinitionId?: string,
    processDefinitionKey?: string,
    processDefinitionKeyIn?: string,
    processDefinitionName?: string,
    processDefinitionNameLike?: string,
    processDefinitionKeyNotIn?: string,
    processInstanceBusinessKey?: string,
    processInstanceBusinessKeyLike?: string,
    rootProcessInstances?: boolean,
    finished?: boolean,
    unfinished?: boolean,
    withIncidents?: boolean,
    withRootIncidents?: boolean,
    incidentType?: string,
    incidentStatus?: 'open' | 'resolved',
    incidentMessage?: string,
    incidentMessageLike?: string,
    startedBefore?: string,
    startedAfter?: string,
    finishedBefore?: string,
    finishedAfter?: string,
    executedActivityAfter?: string,
    executedActivityBefore?: string,
    executedJobAfter?: string,
    executedJobBefore?: string,
    startedBy?: string,
    superProcessInstanceId?: string,
    subProcessInstanceId?: string,
    superCaseInstanceId?: string,
    subCaseInstanceId?: string,
    caseInstanceId?: string,
    tenantIdIn?: string,
    withoutTenantId?: boolean,
    executedActivityIdIn?: string,
    activeActivityIdIn?: string,
    active?: boolean,
    suspended?: boolean,
    completed?: boolean,
    externallyTerminated?: boolean,
    internallyTerminated?: boolean,
    variables?: string,
    variableNamesIgnoreCase?: boolean,
    variableValuesIgnoreCase?: boolean,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<Array<HistoricProcessInstanceDto>>;
  public getHistoricProcessInstances(
    sortBy?:
      | 'instanceId'
      | 'definitionId'
      | 'definitionKey'
      | 'definitionName'
      | 'definitionVersion'
      | 'businessKey'
      | 'startTime'
      | 'endTime'
      | 'duration'
      | 'tenantId',
    sortOrder?: 'asc' | 'desc',
    firstResult?: number,
    maxResults?: number,
    processInstanceId?: string,
    processInstanceIds?: string,
    processDefinitionId?: string,
    processDefinitionKey?: string,
    processDefinitionKeyIn?: string,
    processDefinitionName?: string,
    processDefinitionNameLike?: string,
    processDefinitionKeyNotIn?: string,
    processInstanceBusinessKey?: string,
    processInstanceBusinessKeyLike?: string,
    rootProcessInstances?: boolean,
    finished?: boolean,
    unfinished?: boolean,
    withIncidents?: boolean,
    withRootIncidents?: boolean,
    incidentType?: string,
    incidentStatus?: 'open' | 'resolved',
    incidentMessage?: string,
    incidentMessageLike?: string,
    startedBefore?: string,
    startedAfter?: string,
    finishedBefore?: string,
    finishedAfter?: string,
    executedActivityAfter?: string,
    executedActivityBefore?: string,
    executedJobAfter?: string,
    executedJobBefore?: string,
    startedBy?: string,
    superProcessInstanceId?: string,
    subProcessInstanceId?: string,
    superCaseInstanceId?: string,
    subCaseInstanceId?: string,
    caseInstanceId?: string,
    tenantIdIn?: string,
    withoutTenantId?: boolean,
    executedActivityIdIn?: string,
    activeActivityIdIn?: string,
    active?: boolean,
    suspended?: boolean,
    completed?: boolean,
    externallyTerminated?: boolean,
    internallyTerminated?: boolean,
    variables?: string,
    variableNamesIgnoreCase?: boolean,
    variableValuesIgnoreCase?: boolean,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpResponse<Array<HistoricProcessInstanceDto>>>;
  public getHistoricProcessInstances(
    sortBy?:
      | 'instanceId'
      | 'definitionId'
      | 'definitionKey'
      | 'definitionName'
      | 'definitionVersion'
      | 'businessKey'
      | 'startTime'
      | 'endTime'
      | 'duration'
      | 'tenantId',
    sortOrder?: 'asc' | 'desc',
    firstResult?: number,
    maxResults?: number,
    processInstanceId?: string,
    processInstanceIds?: string,
    processDefinitionId?: string,
    processDefinitionKey?: string,
    processDefinitionKeyIn?: string,
    processDefinitionName?: string,
    processDefinitionNameLike?: string,
    processDefinitionKeyNotIn?: string,
    processInstanceBusinessKey?: string,
    processInstanceBusinessKeyLike?: string,
    rootProcessInstances?: boolean,
    finished?: boolean,
    unfinished?: boolean,
    withIncidents?: boolean,
    withRootIncidents?: boolean,
    incidentType?: string,
    incidentStatus?: 'open' | 'resolved',
    incidentMessage?: string,
    incidentMessageLike?: string,
    startedBefore?: string,
    startedAfter?: string,
    finishedBefore?: string,
    finishedAfter?: string,
    executedActivityAfter?: string,
    executedActivityBefore?: string,
    executedJobAfter?: string,
    executedJobBefore?: string,
    startedBy?: string,
    superProcessInstanceId?: string,
    subProcessInstanceId?: string,
    superCaseInstanceId?: string,
    subCaseInstanceId?: string,
    caseInstanceId?: string,
    tenantIdIn?: string,
    withoutTenantId?: boolean,
    executedActivityIdIn?: string,
    activeActivityIdIn?: string,
    active?: boolean,
    suspended?: boolean,
    completed?: boolean,
    externallyTerminated?: boolean,
    internallyTerminated?: boolean,
    variables?: string,
    variableNamesIgnoreCase?: boolean,
    variableValuesIgnoreCase?: boolean,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpEvent<Array<HistoricProcessInstanceDto>>>;
  public getHistoricProcessInstances(
    sortBy?:
      | 'instanceId'
      | 'definitionId'
      | 'definitionKey'
      | 'definitionName'
      | 'definitionVersion'
      | 'businessKey'
      | 'startTime'
      | 'endTime'
      | 'duration'
      | 'tenantId',
    sortOrder?: 'asc' | 'desc',
    firstResult?: number,
    maxResults?: number,
    processInstanceId?: string,
    processInstanceIds?: string,
    processDefinitionId?: string,
    processDefinitionKey?: string,
    processDefinitionKeyIn?: string,
    processDefinitionName?: string,
    processDefinitionNameLike?: string,
    processDefinitionKeyNotIn?: string,
    processInstanceBusinessKey?: string,
    processInstanceBusinessKeyLike?: string,
    rootProcessInstances?: boolean,
    finished?: boolean,
    unfinished?: boolean,
    withIncidents?: boolean,
    withRootIncidents?: boolean,
    incidentType?: string,
    incidentStatus?: 'open' | 'resolved',
    incidentMessage?: string,
    incidentMessageLike?: string,
    startedBefore?: string,
    startedAfter?: string,
    finishedBefore?: string,
    finishedAfter?: string,
    executedActivityAfter?: string,
    executedActivityBefore?: string,
    executedJobAfter?: string,
    executedJobBefore?: string,
    startedBy?: string,
    superProcessInstanceId?: string,
    subProcessInstanceId?: string,
    superCaseInstanceId?: string,
    subCaseInstanceId?: string,
    caseInstanceId?: string,
    tenantIdIn?: string,
    withoutTenantId?: boolean,
    executedActivityIdIn?: string,
    activeActivityIdIn?: string,
    active?: boolean,
    suspended?: boolean,
    completed?: boolean,
    externallyTerminated?: boolean,
    internallyTerminated?: boolean,
    variables?: string,
    variableNamesIgnoreCase?: boolean,
    variableValuesIgnoreCase?: boolean,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<any> {
    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    if (sortBy !== undefined && sortBy !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>sortBy,
        'sortBy'
      );
    }
    if (sortOrder !== undefined && sortOrder !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>sortOrder,
        'sortOrder'
      );
    }
    if (firstResult !== undefined && firstResult !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>firstResult,
        'firstResult'
      );
    }
    if (maxResults !== undefined && maxResults !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>maxResults,
        'maxResults'
      );
    }
    if (processInstanceId !== undefined && processInstanceId !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processInstanceId,
        'processInstanceId'
      );
    }
    if (processInstanceIds !== undefined && processInstanceIds !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processInstanceIds,
        'processInstanceIds'
      );
    }
    if (processDefinitionId !== undefined && processDefinitionId !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processDefinitionId,
        'processDefinitionId'
      );
    }
    if (processDefinitionKey !== undefined && processDefinitionKey !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processDefinitionKey,
        'processDefinitionKey'
      );
    }
    if (
      processDefinitionKeyIn !== undefined &&
      processDefinitionKeyIn !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processDefinitionKeyIn,
        'processDefinitionKeyIn'
      );
    }
    if (processDefinitionName !== undefined && processDefinitionName !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processDefinitionName,
        'processDefinitionName'
      );
    }
    if (
      processDefinitionNameLike !== undefined &&
      processDefinitionNameLike !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processDefinitionNameLike,
        'processDefinitionNameLike'
      );
    }
    if (
      processDefinitionKeyNotIn !== undefined &&
      processDefinitionKeyNotIn !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processDefinitionKeyNotIn,
        'processDefinitionKeyNotIn'
      );
    }
    if (
      processInstanceBusinessKey !== undefined &&
      processInstanceBusinessKey !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processInstanceBusinessKey,
        'processInstanceBusinessKey'
      );
    }
    if (
      processInstanceBusinessKeyLike !== undefined &&
      processInstanceBusinessKeyLike !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processInstanceBusinessKeyLike,
        'processInstanceBusinessKeyLike'
      );
    }
    if (rootProcessInstances !== undefined && rootProcessInstances !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>rootProcessInstances,
        'rootProcessInstances'
      );
    }
    if (finished !== undefined && finished !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>finished,
        'finished'
      );
    }
    if (unfinished !== undefined && unfinished !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>unfinished,
        'unfinished'
      );
    }
    if (withIncidents !== undefined && withIncidents !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>withIncidents,
        'withIncidents'
      );
    }
    if (withRootIncidents !== undefined && withRootIncidents !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>withRootIncidents,
        'withRootIncidents'
      );
    }
    if (incidentType !== undefined && incidentType !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>incidentType,
        'incidentType'
      );
    }
    if (incidentStatus !== undefined && incidentStatus !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>incidentStatus,
        'incidentStatus'
      );
    }
    if (incidentMessage !== undefined && incidentMessage !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>incidentMessage,
        'incidentMessage'
      );
    }
    if (incidentMessageLike !== undefined && incidentMessageLike !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>incidentMessageLike,
        'incidentMessageLike'
      );
    }
    if (startedBefore !== undefined && startedBefore !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>startedBefore,
        'startedBefore'
      );
    }
    if (startedAfter !== undefined && startedAfter !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>startedAfter,
        'startedAfter'
      );
    }
    if (finishedBefore !== undefined && finishedBefore !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>finishedBefore,
        'finishedBefore'
      );
    }
    if (finishedAfter !== undefined && finishedAfter !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>finishedAfter,
        'finishedAfter'
      );
    }
    if (executedActivityAfter !== undefined && executedActivityAfter !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>executedActivityAfter,
        'executedActivityAfter'
      );
    }
    if (
      executedActivityBefore !== undefined &&
      executedActivityBefore !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>executedActivityBefore,
        'executedActivityBefore'
      );
    }
    if (executedJobAfter !== undefined && executedJobAfter !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>executedJobAfter,
        'executedJobAfter'
      );
    }
    if (executedJobBefore !== undefined && executedJobBefore !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>executedJobBefore,
        'executedJobBefore'
      );
    }
    if (startedBy !== undefined && startedBy !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>startedBy,
        'startedBy'
      );
    }
    if (
      superProcessInstanceId !== undefined &&
      superProcessInstanceId !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>superProcessInstanceId,
        'superProcessInstanceId'
      );
    }
    if (subProcessInstanceId !== undefined && subProcessInstanceId !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>subProcessInstanceId,
        'subProcessInstanceId'
      );
    }
    if (superCaseInstanceId !== undefined && superCaseInstanceId !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>superCaseInstanceId,
        'superCaseInstanceId'
      );
    }
    if (subCaseInstanceId !== undefined && subCaseInstanceId !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>subCaseInstanceId,
        'subCaseInstanceId'
      );
    }
    if (caseInstanceId !== undefined && caseInstanceId !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>caseInstanceId,
        'caseInstanceId'
      );
    }
    if (tenantIdIn !== undefined && tenantIdIn !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>tenantIdIn,
        'tenantIdIn'
      );
    }
    if (withoutTenantId !== undefined && withoutTenantId !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>withoutTenantId,
        'withoutTenantId'
      );
    }
    if (executedActivityIdIn !== undefined && executedActivityIdIn !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>executedActivityIdIn,
        'executedActivityIdIn'
      );
    }
    if (activeActivityIdIn !== undefined && activeActivityIdIn !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>activeActivityIdIn,
        'activeActivityIdIn'
      );
    }
    if (active !== undefined && active !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>active,
        'active'
      );
    }
    if (suspended !== undefined && suspended !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>suspended,
        'suspended'
      );
    }
    if (completed !== undefined && completed !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>completed,
        'completed'
      );
    }
    if (externallyTerminated !== undefined && externallyTerminated !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>externallyTerminated,
        'externallyTerminated'
      );
    }
    if (internallyTerminated !== undefined && internallyTerminated !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>internallyTerminated,
        'internallyTerminated'
      );
    }
    if (variables !== undefined && variables !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>variables,
        'variables'
      );
    }
    if (
      variableNamesIgnoreCase !== undefined &&
      variableNamesIgnoreCase !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>variableNamesIgnoreCase,
        'variableNamesIgnoreCase'
      );
    }
    if (
      variableValuesIgnoreCase !== undefined &&
      variableValuesIgnoreCase !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>variableValuesIgnoreCase,
        'variableValuesIgnoreCase'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    let localVarHttpHeaderAcceptSelected: string | undefined =
      options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected =
        this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Accept',
        localVarHttpHeaderAcceptSelected
      );
    }

    let localVarHttpContext: HttpContext | undefined =
      options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (
        this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
      ) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    return this.httpClient.get<Array<HistoricProcessInstanceDto>>(
      `${this.configuration.basePath}/history/process-instance`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Get List Count
   * Queries for the number of historic process instances that fulfill the given parameters. Takes the same parameters as the [Get Process Instances](https://docs.camunda.org/manual/7.16/reference/rest/history/process-instance/get-process-instance-query/) method.
   * @param processInstanceId Filter by process instance id.
   * @param processInstanceIds Filter by process instance ids. Filter by a comma-separated list of &#x60;Strings&#x60;.
   * @param processDefinitionId Filter by the process definition the instances run on.
   * @param processDefinitionKey Filter by the key of the process definition the instances run on.
   * @param processDefinitionKeyIn Filter by a list of process definition keys. A process instance must have one of the given process definition keys. Filter by a comma-separated list of &#x60;Strings&#x60;.
   * @param processDefinitionName Filter by the name of the process definition the instances run on.
   * @param processDefinitionNameLike Filter by process definition names that the parameter is a substring of.
   * @param processDefinitionKeyNotIn Exclude instances that belong to a set of process definitions. Filter by a comma-separated list of &#x60;Strings&#x60;.
   * @param processInstanceBusinessKey Filter by process instance business key.
   * @param processInstanceBusinessKeyLike Filter by process instance business key that the parameter is a substring of.
   * @param rootProcessInstances Restrict the query to all process instances that are top level process instances.
   * @param finished Only include finished process instances. This flag includes all process instances that are completed or terminated. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
   * @param unfinished Only include unfinished process instances. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
   * @param withIncidents Only include process instances which have an incident. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
   * @param withRootIncidents Only include process instances which have a root incident. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
   * @param incidentType Filter by the incident type. See the [User Guide](https://docs.camunda.org/manual/7.16/user-guide/process-engine/incidents/#incident-types) for a list of incident types.
   * @param incidentStatus Only include process instances which have an incident in status either open or resolved. To get all process instances, use the query parameter withIncidents.
   * @param incidentMessage Filter by the incident message. Exact match.
   * @param incidentMessageLike Filter by the incident message that the parameter is a substring of.
   * @param startedBefore Restrict to instances that were started before the given date. By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/), the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
   * @param startedAfter Restrict to instances that were started after the given date. By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/), the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
   * @param finishedBefore Restrict to instances that were finished before the given date. By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/), the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
   * @param finishedAfter Restrict to instances that were finished after the given date. By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/), the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
   * @param executedActivityAfter Restrict to instances that executed an activity after the given date (inclusive). By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/), the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
   * @param executedActivityBefore Restrict to instances that executed an activity before the given date (inclusive). By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/), the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
   * @param executedJobAfter Restrict to instances that executed an job after the given date (inclusive). By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/), the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
   * @param executedJobBefore Restrict to instances that executed an job before the given date (inclusive). By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/), the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
   * @param startedBy Only include process instances that were started by the given user.
   * @param superProcessInstanceId Restrict query to all process instances that are sub process instances of the given process instance. Takes a process instance id.
   * @param subProcessInstanceId Restrict query to one process instance that has a sub process instance with the given id.
   * @param superCaseInstanceId Restrict query to all process instances that are sub process instances of the given case instance. Takes a case instance id.
   * @param subCaseInstanceId Restrict query to one process instance that has a sub case instance with the given id.
   * @param caseInstanceId Restrict query to all process instances that are sub process instances of the given case instance. Takes a case instance id.
   * @param tenantIdIn Filter by a list of tenant ids. A process instance must have one of the given tenant ids. Filter by a comma-separated list of &#x60;Strings&#x60;
   * @param withoutTenantId Only include historic process instances which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
   * @param executedActivityIdIn Restrict to instances that executed an activity with one of given ids. Filter by a comma-separated list of &#x60;Strings&#x60;
   * @param activeActivityIdIn Restrict to instances that have an active activity with one of given ids. Filter by a comma-separated list of &#x60;Strings&#x60;
   * @param active Restrict to instances that are active.
   * @param suspended Restrict to instances that are suspended.
   * @param completed Restrict to instances that are completed.
   * @param externallyTerminated Restrict to instances that are externallyTerminated.
   * @param internallyTerminated Restrict to instances that are internallyTerminated.
   * @param variables Only include process instances that have/had variables with certain values. Variable filtering expressions are comma-separated and are structured as follows: A valid parameter value has the form &#x60;key_operator_value&#x60;. &#x60;key&#x60; is the variable name, &#x60;operator&#x60; is the comparison operator to be used and &#x60;value&#x60; the variable value.  **Note:** Values are always treated as String objects on server side.  Valid operator values are: &#x60;eq&#x60; - equal to; &#x60;neq&#x60; - not equal to; &#x60;gt&#x60; - greater than; &#x60;gteq&#x60; - greater than or equal to; &#x60;lt&#x60; - lower than; &#x60;lteq&#x60; - lower than or equal to; &#x60;like&#x60;.  Key and value may not contain underscore or comma characters.
   * @param variableNamesIgnoreCase Match all variable names provided in variables case-insensitively. If set to &#x60;true&#x60; variableName and variablename are treated as equal.
   * @param variableValuesIgnoreCase Match all variable values provided in variables case-insensitively. If set to &#x60;true&#x60; variableValue and variablevalue are treated as equal.
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getHistoricProcessInstancesCount(
    processInstanceId?: string,
    processInstanceIds?: string,
    processDefinitionId?: string,
    processDefinitionKey?: string,
    processDefinitionKeyIn?: string,
    processDefinitionName?: string,
    processDefinitionNameLike?: string,
    processDefinitionKeyNotIn?: string,
    processInstanceBusinessKey?: string,
    processInstanceBusinessKeyLike?: string,
    rootProcessInstances?: boolean,
    finished?: boolean,
    unfinished?: boolean,
    withIncidents?: boolean,
    withRootIncidents?: boolean,
    incidentType?: string,
    incidentStatus?: 'open' | 'resolved',
    incidentMessage?: string,
    incidentMessageLike?: string,
    startedBefore?: string,
    startedAfter?: string,
    finishedBefore?: string,
    finishedAfter?: string,
    executedActivityAfter?: string,
    executedActivityBefore?: string,
    executedJobAfter?: string,
    executedJobBefore?: string,
    startedBy?: string,
    superProcessInstanceId?: string,
    subProcessInstanceId?: string,
    superCaseInstanceId?: string,
    subCaseInstanceId?: string,
    caseInstanceId?: string,
    tenantIdIn?: string,
    withoutTenantId?: boolean,
    executedActivityIdIn?: string,
    activeActivityIdIn?: string,
    active?: boolean,
    suspended?: boolean,
    completed?: boolean,
    externallyTerminated?: boolean,
    internallyTerminated?: boolean,
    variables?: string,
    variableNamesIgnoreCase?: boolean,
    variableValuesIgnoreCase?: boolean,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<CountResultDto>;
  public getHistoricProcessInstancesCount(
    processInstanceId?: string,
    processInstanceIds?: string,
    processDefinitionId?: string,
    processDefinitionKey?: string,
    processDefinitionKeyIn?: string,
    processDefinitionName?: string,
    processDefinitionNameLike?: string,
    processDefinitionKeyNotIn?: string,
    processInstanceBusinessKey?: string,
    processInstanceBusinessKeyLike?: string,
    rootProcessInstances?: boolean,
    finished?: boolean,
    unfinished?: boolean,
    withIncidents?: boolean,
    withRootIncidents?: boolean,
    incidentType?: string,
    incidentStatus?: 'open' | 'resolved',
    incidentMessage?: string,
    incidentMessageLike?: string,
    startedBefore?: string,
    startedAfter?: string,
    finishedBefore?: string,
    finishedAfter?: string,
    executedActivityAfter?: string,
    executedActivityBefore?: string,
    executedJobAfter?: string,
    executedJobBefore?: string,
    startedBy?: string,
    superProcessInstanceId?: string,
    subProcessInstanceId?: string,
    superCaseInstanceId?: string,
    subCaseInstanceId?: string,
    caseInstanceId?: string,
    tenantIdIn?: string,
    withoutTenantId?: boolean,
    executedActivityIdIn?: string,
    activeActivityIdIn?: string,
    active?: boolean,
    suspended?: boolean,
    completed?: boolean,
    externallyTerminated?: boolean,
    internallyTerminated?: boolean,
    variables?: string,
    variableNamesIgnoreCase?: boolean,
    variableValuesIgnoreCase?: boolean,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpResponse<CountResultDto>>;
  public getHistoricProcessInstancesCount(
    processInstanceId?: string,
    processInstanceIds?: string,
    processDefinitionId?: string,
    processDefinitionKey?: string,
    processDefinitionKeyIn?: string,
    processDefinitionName?: string,
    processDefinitionNameLike?: string,
    processDefinitionKeyNotIn?: string,
    processInstanceBusinessKey?: string,
    processInstanceBusinessKeyLike?: string,
    rootProcessInstances?: boolean,
    finished?: boolean,
    unfinished?: boolean,
    withIncidents?: boolean,
    withRootIncidents?: boolean,
    incidentType?: string,
    incidentStatus?: 'open' | 'resolved',
    incidentMessage?: string,
    incidentMessageLike?: string,
    startedBefore?: string,
    startedAfter?: string,
    finishedBefore?: string,
    finishedAfter?: string,
    executedActivityAfter?: string,
    executedActivityBefore?: string,
    executedJobAfter?: string,
    executedJobBefore?: string,
    startedBy?: string,
    superProcessInstanceId?: string,
    subProcessInstanceId?: string,
    superCaseInstanceId?: string,
    subCaseInstanceId?: string,
    caseInstanceId?: string,
    tenantIdIn?: string,
    withoutTenantId?: boolean,
    executedActivityIdIn?: string,
    activeActivityIdIn?: string,
    active?: boolean,
    suspended?: boolean,
    completed?: boolean,
    externallyTerminated?: boolean,
    internallyTerminated?: boolean,
    variables?: string,
    variableNamesIgnoreCase?: boolean,
    variableValuesIgnoreCase?: boolean,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpEvent<CountResultDto>>;
  public getHistoricProcessInstancesCount(
    processInstanceId?: string,
    processInstanceIds?: string,
    processDefinitionId?: string,
    processDefinitionKey?: string,
    processDefinitionKeyIn?: string,
    processDefinitionName?: string,
    processDefinitionNameLike?: string,
    processDefinitionKeyNotIn?: string,
    processInstanceBusinessKey?: string,
    processInstanceBusinessKeyLike?: string,
    rootProcessInstances?: boolean,
    finished?: boolean,
    unfinished?: boolean,
    withIncidents?: boolean,
    withRootIncidents?: boolean,
    incidentType?: string,
    incidentStatus?: 'open' | 'resolved',
    incidentMessage?: string,
    incidentMessageLike?: string,
    startedBefore?: string,
    startedAfter?: string,
    finishedBefore?: string,
    finishedAfter?: string,
    executedActivityAfter?: string,
    executedActivityBefore?: string,
    executedJobAfter?: string,
    executedJobBefore?: string,
    startedBy?: string,
    superProcessInstanceId?: string,
    subProcessInstanceId?: string,
    superCaseInstanceId?: string,
    subCaseInstanceId?: string,
    caseInstanceId?: string,
    tenantIdIn?: string,
    withoutTenantId?: boolean,
    executedActivityIdIn?: string,
    activeActivityIdIn?: string,
    active?: boolean,
    suspended?: boolean,
    completed?: boolean,
    externallyTerminated?: boolean,
    internallyTerminated?: boolean,
    variables?: string,
    variableNamesIgnoreCase?: boolean,
    variableValuesIgnoreCase?: boolean,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<any> {
    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    if (processInstanceId !== undefined && processInstanceId !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processInstanceId,
        'processInstanceId'
      );
    }
    if (processInstanceIds !== undefined && processInstanceIds !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processInstanceIds,
        'processInstanceIds'
      );
    }
    if (processDefinitionId !== undefined && processDefinitionId !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processDefinitionId,
        'processDefinitionId'
      );
    }
    if (processDefinitionKey !== undefined && processDefinitionKey !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processDefinitionKey,
        'processDefinitionKey'
      );
    }
    if (
      processDefinitionKeyIn !== undefined &&
      processDefinitionKeyIn !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processDefinitionKeyIn,
        'processDefinitionKeyIn'
      );
    }
    if (processDefinitionName !== undefined && processDefinitionName !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processDefinitionName,
        'processDefinitionName'
      );
    }
    if (
      processDefinitionNameLike !== undefined &&
      processDefinitionNameLike !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processDefinitionNameLike,
        'processDefinitionNameLike'
      );
    }
    if (
      processDefinitionKeyNotIn !== undefined &&
      processDefinitionKeyNotIn !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processDefinitionKeyNotIn,
        'processDefinitionKeyNotIn'
      );
    }
    if (
      processInstanceBusinessKey !== undefined &&
      processInstanceBusinessKey !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processInstanceBusinessKey,
        'processInstanceBusinessKey'
      );
    }
    if (
      processInstanceBusinessKeyLike !== undefined &&
      processInstanceBusinessKeyLike !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>processInstanceBusinessKeyLike,
        'processInstanceBusinessKeyLike'
      );
    }
    if (rootProcessInstances !== undefined && rootProcessInstances !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>rootProcessInstances,
        'rootProcessInstances'
      );
    }
    if (finished !== undefined && finished !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>finished,
        'finished'
      );
    }
    if (unfinished !== undefined && unfinished !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>unfinished,
        'unfinished'
      );
    }
    if (withIncidents !== undefined && withIncidents !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>withIncidents,
        'withIncidents'
      );
    }
    if (withRootIncidents !== undefined && withRootIncidents !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>withRootIncidents,
        'withRootIncidents'
      );
    }
    if (incidentType !== undefined && incidentType !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>incidentType,
        'incidentType'
      );
    }
    if (incidentStatus !== undefined && incidentStatus !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>incidentStatus,
        'incidentStatus'
      );
    }
    if (incidentMessage !== undefined && incidentMessage !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>incidentMessage,
        'incidentMessage'
      );
    }
    if (incidentMessageLike !== undefined && incidentMessageLike !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>incidentMessageLike,
        'incidentMessageLike'
      );
    }
    if (startedBefore !== undefined && startedBefore !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>startedBefore,
        'startedBefore'
      );
    }
    if (startedAfter !== undefined && startedAfter !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>startedAfter,
        'startedAfter'
      );
    }
    if (finishedBefore !== undefined && finishedBefore !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>finishedBefore,
        'finishedBefore'
      );
    }
    if (finishedAfter !== undefined && finishedAfter !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>finishedAfter,
        'finishedAfter'
      );
    }
    if (executedActivityAfter !== undefined && executedActivityAfter !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>executedActivityAfter,
        'executedActivityAfter'
      );
    }
    if (
      executedActivityBefore !== undefined &&
      executedActivityBefore !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>executedActivityBefore,
        'executedActivityBefore'
      );
    }
    if (executedJobAfter !== undefined && executedJobAfter !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>executedJobAfter,
        'executedJobAfter'
      );
    }
    if (executedJobBefore !== undefined && executedJobBefore !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>executedJobBefore,
        'executedJobBefore'
      );
    }
    if (startedBy !== undefined && startedBy !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>startedBy,
        'startedBy'
      );
    }
    if (
      superProcessInstanceId !== undefined &&
      superProcessInstanceId !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>superProcessInstanceId,
        'superProcessInstanceId'
      );
    }
    if (subProcessInstanceId !== undefined && subProcessInstanceId !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>subProcessInstanceId,
        'subProcessInstanceId'
      );
    }
    if (superCaseInstanceId !== undefined && superCaseInstanceId !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>superCaseInstanceId,
        'superCaseInstanceId'
      );
    }
    if (subCaseInstanceId !== undefined && subCaseInstanceId !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>subCaseInstanceId,
        'subCaseInstanceId'
      );
    }
    if (caseInstanceId !== undefined && caseInstanceId !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>caseInstanceId,
        'caseInstanceId'
      );
    }
    if (tenantIdIn !== undefined && tenantIdIn !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>tenantIdIn,
        'tenantIdIn'
      );
    }
    if (withoutTenantId !== undefined && withoutTenantId !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>withoutTenantId,
        'withoutTenantId'
      );
    }
    if (executedActivityIdIn !== undefined && executedActivityIdIn !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>executedActivityIdIn,
        'executedActivityIdIn'
      );
    }
    if (activeActivityIdIn !== undefined && activeActivityIdIn !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>activeActivityIdIn,
        'activeActivityIdIn'
      );
    }
    if (active !== undefined && active !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>active,
        'active'
      );
    }
    if (suspended !== undefined && suspended !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>suspended,
        'suspended'
      );
    }
    if (completed !== undefined && completed !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>completed,
        'completed'
      );
    }
    if (externallyTerminated !== undefined && externallyTerminated !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>externallyTerminated,
        'externallyTerminated'
      );
    }
    if (internallyTerminated !== undefined && internallyTerminated !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>internallyTerminated,
        'internallyTerminated'
      );
    }
    if (variables !== undefined && variables !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>variables,
        'variables'
      );
    }
    if (
      variableNamesIgnoreCase !== undefined &&
      variableNamesIgnoreCase !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>variableNamesIgnoreCase,
        'variableNamesIgnoreCase'
      );
    }
    if (
      variableValuesIgnoreCase !== undefined &&
      variableValuesIgnoreCase !== null
    ) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>variableValuesIgnoreCase,
        'variableValuesIgnoreCase'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    let localVarHttpHeaderAcceptSelected: string | undefined =
      options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected =
        this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Accept',
        localVarHttpHeaderAcceptSelected
      );
    }

    let localVarHttpContext: HttpContext | undefined =
      options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (
        this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
      ) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    return this.httpClient.get<CountResultDto>(
      `${this.configuration.basePath}/history/process-instance/count`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Get List (POST)
   * Queries for historic process instances that fulfill the given parameters. This method is slightly more powerful than the [Get Process Instance](https://docs.camunda.org/manual/7.16/reference/rest/history/process-instance/get-process-instance-query/) because it allows filtering by multiple process variables of types &#x60;String&#x60;, &#x60;Number&#x60; or &#x60;Boolean&#x60;.
   * @param firstResult Pagination of results. Specifies the index of the first result to return.
   * @param maxResults Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left.
   * @param historicProcessInstanceQueryDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public queryHistoricProcessInstances(
    firstResult?: number,
    maxResults?: number,
    historicProcessInstanceQueryDto?: HistoricProcessInstanceQueryDto,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<Array<HistoricProcessInstanceDto>>;
  public queryHistoricProcessInstances(
    firstResult?: number,
    maxResults?: number,
    historicProcessInstanceQueryDto?: HistoricProcessInstanceQueryDto,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpResponse<Array<HistoricProcessInstanceDto>>>;
  public queryHistoricProcessInstances(
    firstResult?: number,
    maxResults?: number,
    historicProcessInstanceQueryDto?: HistoricProcessInstanceQueryDto,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpEvent<Array<HistoricProcessInstanceDto>>>;
  public queryHistoricProcessInstances(
    firstResult?: number,
    maxResults?: number,
    historicProcessInstanceQueryDto?: HistoricProcessInstanceQueryDto,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<any> {
    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    if (firstResult !== undefined && firstResult !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>firstResult,
        'firstResult'
      );
    }
    if (maxResults !== undefined && maxResults !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>maxResults,
        'maxResults'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    let localVarHttpHeaderAcceptSelected: string | undefined =
      options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected =
        this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Accept',
        localVarHttpHeaderAcceptSelected
      );
    }

    let localVarHttpContext: HttpContext | undefined =
      options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined =
      this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Content-Type',
        httpContentTypeSelected
      );
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (
        this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
      ) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    return this.httpClient.post<Array<HistoricProcessInstanceDto>>(
      `${this.configuration.basePath}/history/process-instance`,
      historicProcessInstanceQueryDto,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Get List Count (POST)
   * Queries for the number of historic process instances that fulfill the given parameters. This method takes the same message body as the [Get Process Instances (POST)](https://docs.camunda.org/manual/7.16/reference/rest/history/process-instance/get-process-instance-query/) method and therefore it is slightly more powerful than the [Get Process Instance Count](https://docs.camunda.org/manual/7.16/reference/rest/history/process-instance/post-process-instance-query-count/) method.
   * @param historicProcessInstanceQueryDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public queryHistoricProcessInstancesCount(
    historicProcessInstanceQueryDto?: HistoricProcessInstanceQueryDto,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<CountResultDto>;
  public queryHistoricProcessInstancesCount(
    historicProcessInstanceQueryDto?: HistoricProcessInstanceQueryDto,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpResponse<CountResultDto>>;
  public queryHistoricProcessInstancesCount(
    historicProcessInstanceQueryDto?: HistoricProcessInstanceQueryDto,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpEvent<CountResultDto>>;
  public queryHistoricProcessInstancesCount(
    historicProcessInstanceQueryDto?: HistoricProcessInstanceQueryDto,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<any> {
    let localVarHeaders = this.defaultHeaders;

    let localVarHttpHeaderAcceptSelected: string | undefined =
      options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected =
        this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Accept',
        localVarHttpHeaderAcceptSelected
      );
    }

    let localVarHttpContext: HttpContext | undefined =
      options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined =
      this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Content-Type',
        httpContentTypeSelected
      );
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (
        this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
      ) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    return this.httpClient.post<CountResultDto>(
      `${this.configuration.basePath}/history/process-instance/count`,
      historicProcessInstanceQueryDto,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Set Removal Time Async (POST)
   * Sets the removal time to multiple historic process instances asynchronously (batch).  At least &#x60;historicProcessInstanceIds&#x60; or &#x60;historicProcessInstanceQuery&#x60; has to be provided. If both are provided, all instances matching query criterion and instances from the list will be updated with a removal time.
   * @param setRemovalTimeToHistoricProcessInstancesDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public setRemovalTimeAsync(
    setRemovalTimeToHistoricProcessInstancesDto?: SetRemovalTimeToHistoricProcessInstancesDto,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<BatchDto>;
  public setRemovalTimeAsync(
    setRemovalTimeToHistoricProcessInstancesDto?: SetRemovalTimeToHistoricProcessInstancesDto,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpResponse<BatchDto>>;
  public setRemovalTimeAsync(
    setRemovalTimeToHistoricProcessInstancesDto?: SetRemovalTimeToHistoricProcessInstancesDto,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpEvent<BatchDto>>;
  public setRemovalTimeAsync(
    setRemovalTimeToHistoricProcessInstancesDto?: SetRemovalTimeToHistoricProcessInstancesDto,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<any> {
    let localVarHeaders = this.defaultHeaders;

    let localVarHttpHeaderAcceptSelected: string | undefined =
      options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected =
        this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Accept',
        localVarHttpHeaderAcceptSelected
      );
    }

    let localVarHttpContext: HttpContext | undefined =
      options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined =
      this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Content-Type',
        httpContentTypeSelected
      );
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (
        this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
      ) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    return this.httpClient.post<BatchDto>(
      `${this.configuration.basePath}/history/process-instance/set-removal-time`,
      setRemovalTimeToHistoricProcessInstancesDto,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }
}
