//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent, HttpParameterCodec, HttpContext }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from 'src/app/shared/services/camunda-api/encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { CountResultDto } from 'src/app/shared/services/camunda-api/model/countResultDto';
// @ts-ignore
import { ExceptionDto } from 'src/app/shared/services/camunda-api/model/exceptionDto';
// @ts-ignore
import { HistoricDetailDto } from 'src/app/shared/services/camunda-api/model/historicDetailDto';
// @ts-ignore
import { HistoricDetailQueryDto } from 'src/app/shared/services/camunda-api/model/historicDetailQueryDto';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from 'src/app/shared/services/camunda-api/variables';
import { Configuration }                                     from 'src/app/shared/services/camunda-api/configuration';



@Injectable({
  providedIn: 'root'
})
export class HistoricDetailService {

    protected basePath = 'http://localhost:8080/engine-rest';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key,
                        (value as Date).toISOString().substr(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * Get Historic Details
     * Queries for historic details that fulfill the given parameters. The size of the result set can be retrieved by using the [Get Historic Detail Count](https://docs.camunda.org/manual/7.16/reference/rest/history/detail/get-detail-query-count/) method.
     * @param processInstanceId Filter by process instance id.
     * @param processInstanceIdIn Only include historic details which belong to one of the passed comma-separated process instance ids.
     * @param executionId Filter by execution id.
     * @param taskId Filter by task id.
     * @param activityInstanceId Filter by activity instance id.
     * @param caseInstanceId Filter by case instance id.
     * @param caseExecutionId Filter by case execution id.
     * @param variableInstanceId Filter by variable instance id.
     * @param variableTypeIn Only include historic details where the variable updates belong to one of the passed comma-separated list of variable types. A list of all supported variable types can be found [here](https://docs.camunda.org/manual/7.16/user-guide/process-engine/variables/#supported-variable-values). **Note:** All non-primitive variables are associated with the type &#x60;serializable&#x60;.
     * @param tenantIdIn Filter by a comma-separated list of tenant ids.
     * @param withoutTenantId Only include historic details that belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
     * @param userOperationId Filter by a user operation id.
     * @param formFields Only include &#x60;HistoricFormFields&#x60;. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
     * @param variableUpdates Only include &#x60;HistoricVariableUpdates&#x60;. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
     * @param excludeTaskDetails Excludes all task-related &#x60;HistoricDetails&#x60;, so only items which have no task id set will be selected. When this parameter is used together with &#x60;taskId&#x60;, this call is ignored and task details are not excluded. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
     * @param initial Restrict to historic variable updates that contain only initial variable values. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
     * @param occurredBefore Restrict to historic details that occured before the given date (including the date). Default [format](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/) &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., 2013-01-23T14:42:45.000+0200.
     * @param occurredAfter Restrict to historic details that occured after the given date (including the date). Default [format](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/) &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., 2013-01-23T14:42:45.000+0200.
     * @param sortBy Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter.
     * @param sortOrder Sort the results in a given order. Values may be asc for ascending order or desc for descending order. Must be used in conjunction with the sortBy parameter.
     * @param firstResult Pagination of results. Specifies the index of the first result to return.
     * @param maxResults Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left.
     * @param deserializeValues Determines whether serializable variable values (typically variables that store custom Java objects) should be deserialized on server side (default &#x60;true&#x60;).  If set to &#x60;true&#x60;, a serializable variable will be deserialized on server side and transformed to JSON using [Jackson\&#39;s](https://github.com/FasterXML/jackson) POJO/bean property introspection feature. Note that this requires the Java classes of the variable value to be on the REST API\&#39;s classpath.  If set to &#x60;false&#x60;, a serializable variable will be returned in its serialized format. For example, a variable that is serialized as XML will be returned as a JSON string containing XML.  **Note:** While &#x60;true&#x60; is the default value for reasons of backward compatibility, we recommend setting this parameter to &#x60;false&#x60; when developing web applications that are independent of the Java process applications deployed to the engine.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getHistoricDetails(processInstanceId?: string, processInstanceIdIn?: string, executionId?: string, taskId?: string, activityInstanceId?: string, caseInstanceId?: string, caseExecutionId?: string, variableInstanceId?: string, variableTypeIn?: string, tenantIdIn?: string, withoutTenantId?: boolean, userOperationId?: string, formFields?: boolean, variableUpdates?: boolean, excludeTaskDetails?: boolean, initial?: boolean, occurredBefore?: string, occurredAfter?: string, sortBy?: 'processInstanceId' | 'variableName' | 'variableType' | 'variableRevision' | 'formPropertyId' | 'time' | 'occurrence' | 'tenantId', sortOrder?: 'asc' | 'desc', firstResult?: number, maxResults?: number, deserializeValues?: boolean, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<Array<HistoricDetailDto>>;
    public getHistoricDetails(processInstanceId?: string, processInstanceIdIn?: string, executionId?: string, taskId?: string, activityInstanceId?: string, caseInstanceId?: string, caseExecutionId?: string, variableInstanceId?: string, variableTypeIn?: string, tenantIdIn?: string, withoutTenantId?: boolean, userOperationId?: string, formFields?: boolean, variableUpdates?: boolean, excludeTaskDetails?: boolean, initial?: boolean, occurredBefore?: string, occurredAfter?: string, sortBy?: 'processInstanceId' | 'variableName' | 'variableType' | 'variableRevision' | 'formPropertyId' | 'time' | 'occurrence' | 'tenantId', sortOrder?: 'asc' | 'desc', firstResult?: number, maxResults?: number, deserializeValues?: boolean, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpResponse<Array<HistoricDetailDto>>>;
    public getHistoricDetails(processInstanceId?: string, processInstanceIdIn?: string, executionId?: string, taskId?: string, activityInstanceId?: string, caseInstanceId?: string, caseExecutionId?: string, variableInstanceId?: string, variableTypeIn?: string, tenantIdIn?: string, withoutTenantId?: boolean, userOperationId?: string, formFields?: boolean, variableUpdates?: boolean, excludeTaskDetails?: boolean, initial?: boolean, occurredBefore?: string, occurredAfter?: string, sortBy?: 'processInstanceId' | 'variableName' | 'variableType' | 'variableRevision' | 'formPropertyId' | 'time' | 'occurrence' | 'tenantId', sortOrder?: 'asc' | 'desc', firstResult?: number, maxResults?: number, deserializeValues?: boolean, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpEvent<Array<HistoricDetailDto>>>;
    public getHistoricDetails(processInstanceId?: string, processInstanceIdIn?: string, executionId?: string, taskId?: string, activityInstanceId?: string, caseInstanceId?: string, caseExecutionId?: string, variableInstanceId?: string, variableTypeIn?: string, tenantIdIn?: string, withoutTenantId?: boolean, userOperationId?: string, formFields?: boolean, variableUpdates?: boolean, excludeTaskDetails?: boolean, initial?: boolean, occurredBefore?: string, occurredAfter?: string, sortBy?: 'processInstanceId' | 'variableName' | 'variableType' | 'variableRevision' | 'formPropertyId' | 'time' | 'occurrence' | 'tenantId', sortOrder?: 'asc' | 'desc', firstResult?: number, maxResults?: number, deserializeValues?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (processInstanceId !== undefined && processInstanceId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>processInstanceId, 'processInstanceId');
        }
        if (processInstanceIdIn !== undefined && processInstanceIdIn !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>processInstanceIdIn, 'processInstanceIdIn');
        }
        if (executionId !== undefined && executionId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>executionId, 'executionId');
        }
        if (taskId !== undefined && taskId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>taskId, 'taskId');
        }
        if (activityInstanceId !== undefined && activityInstanceId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>activityInstanceId, 'activityInstanceId');
        }
        if (caseInstanceId !== undefined && caseInstanceId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>caseInstanceId, 'caseInstanceId');
        }
        if (caseExecutionId !== undefined && caseExecutionId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>caseExecutionId, 'caseExecutionId');
        }
        if (variableInstanceId !== undefined && variableInstanceId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>variableInstanceId, 'variableInstanceId');
        }
        if (variableTypeIn !== undefined && variableTypeIn !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>variableTypeIn, 'variableTypeIn');
        }
        if (tenantIdIn !== undefined && tenantIdIn !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>tenantIdIn, 'tenantIdIn');
        }
        if (withoutTenantId !== undefined && withoutTenantId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>withoutTenantId, 'withoutTenantId');
        }
        if (userOperationId !== undefined && userOperationId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>userOperationId, 'userOperationId');
        }
        if (formFields !== undefined && formFields !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>formFields, 'formFields');
        }
        if (variableUpdates !== undefined && variableUpdates !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>variableUpdates, 'variableUpdates');
        }
        if (excludeTaskDetails !== undefined && excludeTaskDetails !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>excludeTaskDetails, 'excludeTaskDetails');
        }
        if (initial !== undefined && initial !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>initial, 'initial');
        }
        if (occurredBefore !== undefined && occurredBefore !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>occurredBefore, 'occurredBefore');
        }
        if (occurredAfter !== undefined && occurredAfter !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>occurredAfter, 'occurredAfter');
        }
        if (sortBy !== undefined && sortBy !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>sortBy, 'sortBy');
        }
        if (sortOrder !== undefined && sortOrder !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>sortOrder, 'sortOrder');
        }
        if (firstResult !== undefined && firstResult !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>firstResult, 'firstResult');
        }
        if (maxResults !== undefined && maxResults !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>maxResults, 'maxResults');
        }
        if (deserializeValues !== undefined && deserializeValues !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>deserializeValues, 'deserializeValues');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        return this.httpClient.get<Array<HistoricDetailDto>>(`${this.configuration.basePath}/history/detail`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Historic Detail Count
     * Queries for the number of historic details that fulfill the given parameters. Takes the same parameters as the [Get Historic Details](https://docs.camunda.org/manual/7.16/reference/rest/history/detail/get-detail-query/) method.
     * @param processInstanceId Filter by process instance id.
     * @param processInstanceIdIn Only include historic details which belong to one of the passed comma-separated process instance ids.
     * @param executionId Filter by execution id.
     * @param taskId Filter by task id.
     * @param activityInstanceId Filter by activity instance id.
     * @param caseInstanceId Filter by case instance id.
     * @param caseExecutionId Filter by case execution id.
     * @param variableInstanceId Filter by variable instance id.
     * @param variableTypeIn Only include historic details where the variable updates belong to one of the passed comma-separated list of variable types. A list of all supported variable types can be found [here](https://docs.camunda.org/manual/7.16/user-guide/process-engine/variables/#supported-variable-values). **Note:** All non-primitive variables are associated with the type &#x60;serializable&#x60;.
     * @param tenantIdIn Filter by a comma-separated list of tenant ids.
     * @param withoutTenantId Only include historic details that belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
     * @param userOperationId Filter by a user operation id.
     * @param formFields Only include &#x60;HistoricFormFields&#x60;. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
     * @param variableUpdates Only include &#x60;HistoricVariableUpdates&#x60;. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
     * @param excludeTaskDetails Excludes all task-related &#x60;HistoricDetails&#x60;, so only items which have no task id set will be selected. When this parameter is used together with &#x60;taskId&#x60;, this call is ignored and task details are not excluded. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
     * @param initial Restrict to historic variable updates that contain only initial variable values. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
     * @param occurredBefore Restrict to historic details that occured before the given date (including the date). Default [format](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/) &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., 2013-01-23T14:42:45.000+0200.
     * @param occurredAfter Restrict to historic details that occured after the given date (including the date). Default [format](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/) &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;, e.g., 2013-01-23T14:42:45.000+0200.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getHistoricDetailsCount(processInstanceId?: string, processInstanceIdIn?: string, executionId?: string, taskId?: string, activityInstanceId?: string, caseInstanceId?: string, caseExecutionId?: string, variableInstanceId?: string, variableTypeIn?: string, tenantIdIn?: string, withoutTenantId?: boolean, userOperationId?: string, formFields?: boolean, variableUpdates?: boolean, excludeTaskDetails?: boolean, initial?: boolean, occurredBefore?: string, occurredAfter?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<CountResultDto>;
    public getHistoricDetailsCount(processInstanceId?: string, processInstanceIdIn?: string, executionId?: string, taskId?: string, activityInstanceId?: string, caseInstanceId?: string, caseExecutionId?: string, variableInstanceId?: string, variableTypeIn?: string, tenantIdIn?: string, withoutTenantId?: boolean, userOperationId?: string, formFields?: boolean, variableUpdates?: boolean, excludeTaskDetails?: boolean, initial?: boolean, occurredBefore?: string, occurredAfter?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpResponse<CountResultDto>>;
    public getHistoricDetailsCount(processInstanceId?: string, processInstanceIdIn?: string, executionId?: string, taskId?: string, activityInstanceId?: string, caseInstanceId?: string, caseExecutionId?: string, variableInstanceId?: string, variableTypeIn?: string, tenantIdIn?: string, withoutTenantId?: boolean, userOperationId?: string, formFields?: boolean, variableUpdates?: boolean, excludeTaskDetails?: boolean, initial?: boolean, occurredBefore?: string, occurredAfter?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpEvent<CountResultDto>>;
    public getHistoricDetailsCount(processInstanceId?: string, processInstanceIdIn?: string, executionId?: string, taskId?: string, activityInstanceId?: string, caseInstanceId?: string, caseExecutionId?: string, variableInstanceId?: string, variableTypeIn?: string, tenantIdIn?: string, withoutTenantId?: boolean, userOperationId?: string, formFields?: boolean, variableUpdates?: boolean, excludeTaskDetails?: boolean, initial?: boolean, occurredBefore?: string, occurredAfter?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (processInstanceId !== undefined && processInstanceId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>processInstanceId, 'processInstanceId');
        }
        if (processInstanceIdIn !== undefined && processInstanceIdIn !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>processInstanceIdIn, 'processInstanceIdIn');
        }
        if (executionId !== undefined && executionId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>executionId, 'executionId');
        }
        if (taskId !== undefined && taskId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>taskId, 'taskId');
        }
        if (activityInstanceId !== undefined && activityInstanceId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>activityInstanceId, 'activityInstanceId');
        }
        if (caseInstanceId !== undefined && caseInstanceId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>caseInstanceId, 'caseInstanceId');
        }
        if (caseExecutionId !== undefined && caseExecutionId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>caseExecutionId, 'caseExecutionId');
        }
        if (variableInstanceId !== undefined && variableInstanceId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>variableInstanceId, 'variableInstanceId');
        }
        if (variableTypeIn !== undefined && variableTypeIn !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>variableTypeIn, 'variableTypeIn');
        }
        if (tenantIdIn !== undefined && tenantIdIn !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>tenantIdIn, 'tenantIdIn');
        }
        if (withoutTenantId !== undefined && withoutTenantId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>withoutTenantId, 'withoutTenantId');
        }
        if (userOperationId !== undefined && userOperationId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>userOperationId, 'userOperationId');
        }
        if (formFields !== undefined && formFields !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>formFields, 'formFields');
        }
        if (variableUpdates !== undefined && variableUpdates !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>variableUpdates, 'variableUpdates');
        }
        if (excludeTaskDetails !== undefined && excludeTaskDetails !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>excludeTaskDetails, 'excludeTaskDetails');
        }
        if (initial !== undefined && initial !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>initial, 'initial');
        }
        if (occurredBefore !== undefined && occurredBefore !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>occurredBefore, 'occurredBefore');
        }
        if (occurredAfter !== undefined && occurredAfter !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>occurredAfter, 'occurredAfter');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        return this.httpClient.get<CountResultDto>(`${this.configuration.basePath}/history/detail/count`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Historic Detail
     * Retrieves a historic detail by id.
     * @param id The id of the detail.
     * @param deserializeValue Determines whether serializable variable values (typically variables that store custom Java objects) should be deserialized on server side (default &#x60;true&#x60;).  If set to &#x60;true&#x60;, a serializable variable will be deserialized on server side and transformed to JSON using [Jackson\&#39;s](https://github.com/FasterXML/jackson) POJO/bean property introspection feature. Note that this requires the Java classes of the variable value to be on the REST API\&#39;s classpath.  If set to &#x60;false&#x60;, a serializable variable will be returned in its serialized format. For example, a variable that is serialized as XML will be returned as a JSON string containing XML.  **Note:** While &#x60;true&#x60; is the default value for reasons of backward compatibility, we recommend setting this parameter to &#x60;false&#x60; when developing web applications that are independent of the Java process applications deployed to the engine.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public historicDetail(id: string, deserializeValue?: boolean, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HistoricDetailDto>;
    public historicDetail(id: string, deserializeValue?: boolean, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpResponse<HistoricDetailDto>>;
    public historicDetail(id: string, deserializeValue?: boolean, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpEvent<HistoricDetailDto>>;
    public historicDetail(id: string, deserializeValue?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling historicDetail.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (deserializeValue !== undefined && deserializeValue !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>deserializeValue, 'deserializeValue');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        return this.httpClient.get<HistoricDetailDto>(`${this.configuration.basePath}/history/detail/${encodeURIComponent(String(id))}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Historic Detail (Binary)
     * Retrieves the content of a historic variable update by id. Applicable for byte array and file variables.
     * @param id The id of the historic variable update.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public historicDetailBinary(id: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/octet-stream' | '*/*' | 'application/json', context?: HttpContext}): Observable<Blob>;
    public historicDetailBinary(id: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/octet-stream' | '*/*' | 'application/json', context?: HttpContext}): Observable<HttpResponse<Blob>>;
    public historicDetailBinary(id: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/octet-stream' | '*/*' | 'application/json', context?: HttpContext}): Observable<HttpEvent<Blob>>;
    public historicDetailBinary(id: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/octet-stream' | '*/*' | 'application/json', context?: HttpContext}): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling historicDetailBinary.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/octet-stream',
                '*/*',
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        return this.httpClient.get(`${this.configuration.basePath}/history/detail/${encodeURIComponent(String(id))}/data`,
            {
                context: localVarHttpContext,
                responseType: "blob",
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Historic Details (POST)
     * Queries for historic details that fulfill the given parameters. This method is slightly more powerful than the [Get Historic Details](https://docs.camunda.org/manual/7.16/reference/rest/history/detail/get-detail-query/) method because it allows sorting by multiple parameters. The size of the result set can be retrieved by using the [Get Historic Detail Count](https://docs.camunda.org/manual/7.16/reference/rest/history/detail/get-detail-query-count/) method.
     * @param firstResult Pagination of results. Specifies the index of the first result to return.
     * @param maxResults Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left.
     * @param deserializeValues Determines whether serializable variable values (typically variables that store custom Java objects) should be deserialized on server side (default &#x60;true&#x60;).  If set to &#x60;true&#x60;, a serializable variable will be deserialized on server side and transformed to JSON using [Jackson\&#39;s](https://github.com/FasterXML/jackson) POJO/bean property introspection feature. Note that this requires the Java classes of the variable value to be on the REST API\&#39;s classpath.  If set to &#x60;false&#x60;, a serializable variable will be returned in its serialized format. For example, a variable that is serialized as XML will be returned as a JSON string containing XML.  **Note:** While &#x60;true&#x60; is the default value for reasons of backward compatibility, we recommend setting this parameter to &#x60;false&#x60; when developing web applications that are independent of the Java process applications deployed to the engine.
     * @param historicDetailQueryDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public queryHistoricDetails(firstResult?: number, maxResults?: number, deserializeValues?: boolean, historicDetailQueryDto?: HistoricDetailQueryDto, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<Array<HistoricDetailDto>>;
    public queryHistoricDetails(firstResult?: number, maxResults?: number, deserializeValues?: boolean, historicDetailQueryDto?: HistoricDetailQueryDto, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpResponse<Array<HistoricDetailDto>>>;
    public queryHistoricDetails(firstResult?: number, maxResults?: number, deserializeValues?: boolean, historicDetailQueryDto?: HistoricDetailQueryDto, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpEvent<Array<HistoricDetailDto>>>;
    public queryHistoricDetails(firstResult?: number, maxResults?: number, deserializeValues?: boolean, historicDetailQueryDto?: HistoricDetailQueryDto, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (firstResult !== undefined && firstResult !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>firstResult, 'firstResult');
        }
        if (maxResults !== undefined && maxResults !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>maxResults, 'maxResults');
        }
        if (deserializeValues !== undefined && deserializeValues !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>deserializeValues, 'deserializeValues');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        return this.httpClient.post<Array<HistoricDetailDto>>(`${this.configuration.basePath}/history/detail`,
            historicDetailQueryDto,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
