//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent, HttpParameterCodec, HttpContext }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from 'src/app/shared/services/camunda-api/encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { CleanableHistoricProcessInstanceReportResultDto } from 'src/app/shared/services/camunda-api/model/cleanableHistoricProcessInstanceReportResultDto';
// @ts-ignore
import { CountResultDto } from 'src/app/shared/services/camunda-api/model/countResultDto';
// @ts-ignore
import { ExceptionDto } from 'src/app/shared/services/camunda-api/model/exceptionDto';
// @ts-ignore
import { HistoricActivityStatisticsDto } from 'src/app/shared/services/camunda-api/model/historicActivityStatisticsDto';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from 'src/app/shared/services/camunda-api/variables';
import { Configuration }                                     from 'src/app/shared/services/camunda-api/configuration';



@Injectable({
  providedIn: 'root'
})
export class HistoricProcessDefinitionService {

    protected basePath = 'http://localhost:8080/engine-rest';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key,
                        (value as Date).toISOString().substr(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * Get Cleanable Process Instance Report
     * Retrieves a report about a process definition and finished process instances relevant to history cleanup (see [History cleanup](https://docs.camunda.org/manual/7.16/user-guide/process-engine/history/#history-cleanup))  so that you can tune the history time to live. These reports include the count of the finished historic process instances, cleanable process instances and basic process definition data - id, key, name and version. The size of the result set can be retrieved by using the [Get Cleanable Process Instance Report Count](https://docs.camunda.org/manual/7.16/reference/rest/history/process-definition/get-cleanable-process-instance-report-count/) method.
     * @param processDefinitionIdIn Filter by process definition ids. Must be a comma-separated list of process definition ids.
     * @param processDefinitionKeyIn Filter by process definition keys. Must be a comma-separated list of process definition keys.
     * @param tenantIdIn Filter by a comma-separated list of tenant ids. A process definition must have one of the given  tenant ids.
     * @param withoutTenantId Only include process definitions which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
     * @param compact Only include process instances which have more than zero finished instances. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
     * @param sortBy Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter.
     * @param sortOrder Sort the results in a given order. Values may be asc for ascending order or desc for descending order. Must be used in conjunction with the sortBy parameter.
     * @param firstResult Pagination of results. Specifies the index of the first result to return.
     * @param maxResults Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCleanableHistoricProcessInstanceReport(processDefinitionIdIn?: string, processDefinitionKeyIn?: string, tenantIdIn?: string, withoutTenantId?: boolean, compact?: boolean, sortBy?: 'finished', sortOrder?: 'asc' | 'desc', firstResult?: number, maxResults?: number, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<Array<CleanableHistoricProcessInstanceReportResultDto>>;
    public getCleanableHistoricProcessInstanceReport(processDefinitionIdIn?: string, processDefinitionKeyIn?: string, tenantIdIn?: string, withoutTenantId?: boolean, compact?: boolean, sortBy?: 'finished', sortOrder?: 'asc' | 'desc', firstResult?: number, maxResults?: number, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpResponse<Array<CleanableHistoricProcessInstanceReportResultDto>>>;
    public getCleanableHistoricProcessInstanceReport(processDefinitionIdIn?: string, processDefinitionKeyIn?: string, tenantIdIn?: string, withoutTenantId?: boolean, compact?: boolean, sortBy?: 'finished', sortOrder?: 'asc' | 'desc', firstResult?: number, maxResults?: number, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpEvent<Array<CleanableHistoricProcessInstanceReportResultDto>>>;
    public getCleanableHistoricProcessInstanceReport(processDefinitionIdIn?: string, processDefinitionKeyIn?: string, tenantIdIn?: string, withoutTenantId?: boolean, compact?: boolean, sortBy?: 'finished', sortOrder?: 'asc' | 'desc', firstResult?: number, maxResults?: number, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (processDefinitionIdIn !== undefined && processDefinitionIdIn !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>processDefinitionIdIn, 'processDefinitionIdIn');
        }
        if (processDefinitionKeyIn !== undefined && processDefinitionKeyIn !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>processDefinitionKeyIn, 'processDefinitionKeyIn');
        }
        if (tenantIdIn !== undefined && tenantIdIn !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>tenantIdIn, 'tenantIdIn');
        }
        if (withoutTenantId !== undefined && withoutTenantId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>withoutTenantId, 'withoutTenantId');
        }
        if (compact !== undefined && compact !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>compact, 'compact');
        }
        if (sortBy !== undefined && sortBy !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>sortBy, 'sortBy');
        }
        if (sortOrder !== undefined && sortOrder !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>sortOrder, 'sortOrder');
        }
        if (firstResult !== undefined && firstResult !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>firstResult, 'firstResult');
        }
        if (maxResults !== undefined && maxResults !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>maxResults, 'maxResults');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        return this.httpClient.get<Array<CleanableHistoricProcessInstanceReportResultDto>>(`${this.configuration.basePath}/history/process-definition/cleanable-process-instance-report`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Cleanable Process Instance Report Count
     * Queries for the number of report results about a process definition and finished process instances relevant to history cleanup (see [History cleanup](https://docs.camunda.org/manual/7.16/user-guide/process-engine/history/#history-cleanup)). Takes the same parameters as the [Get Cleanable Process Instance Report](https://docs.camunda.org/manual/7.16/reference/rest/history/process-definition/get-cleanable-process-instance-report/) method.
     * @param processDefinitionIdIn Filter by process definition ids. Must be a comma-separated list of process definition ids.
     * @param processDefinitionKeyIn Filter by process definition keys. Must be a comma-separated list of process definition keys.
     * @param tenantIdIn Filter by a comma-separated list of tenant ids. A process definition must have one of the given  tenant ids.
     * @param withoutTenantId Only include process definitions which belong to no tenant. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
     * @param compact Only include process instances which have more than zero finished instances. Value may only be &#x60;true&#x60;, as &#x60;false&#x60; is the default behavior.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCleanableHistoricProcessInstanceReportCount(processDefinitionIdIn?: string, processDefinitionKeyIn?: string, tenantIdIn?: string, withoutTenantId?: boolean, compact?: boolean, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<CountResultDto>;
    public getCleanableHistoricProcessInstanceReportCount(processDefinitionIdIn?: string, processDefinitionKeyIn?: string, tenantIdIn?: string, withoutTenantId?: boolean, compact?: boolean, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpResponse<CountResultDto>>;
    public getCleanableHistoricProcessInstanceReportCount(processDefinitionIdIn?: string, processDefinitionKeyIn?: string, tenantIdIn?: string, withoutTenantId?: boolean, compact?: boolean, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpEvent<CountResultDto>>;
    public getCleanableHistoricProcessInstanceReportCount(processDefinitionIdIn?: string, processDefinitionKeyIn?: string, tenantIdIn?: string, withoutTenantId?: boolean, compact?: boolean, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<any> {

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (processDefinitionIdIn !== undefined && processDefinitionIdIn !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>processDefinitionIdIn, 'processDefinitionIdIn');
        }
        if (processDefinitionKeyIn !== undefined && processDefinitionKeyIn !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>processDefinitionKeyIn, 'processDefinitionKeyIn');
        }
        if (tenantIdIn !== undefined && tenantIdIn !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>tenantIdIn, 'tenantIdIn');
        }
        if (withoutTenantId !== undefined && withoutTenantId !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>withoutTenantId, 'withoutTenantId');
        }
        if (compact !== undefined && compact !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>compact, 'compact');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        return this.httpClient.get<CountResultDto>(`${this.configuration.basePath}/history/process-definition/cleanable-process-instance-report/count`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get Historic Activity Statistics
     * Retrieves historic statistics of a given process definition, grouped by activities. These statistics include the number of running activity instances and, optionally, the number of canceled activity instances, finished activity instances and activity instances which completed a scope (i.e., in BPMN 2.0 manner: a scope is completed by an activity instance when the activity instance consumed a token but did not emit a new token). **Note:** This only includes historic data.
     * @param id The id of the process definition.
     * @param canceled Whether to include the number of canceled activity instances in the result or not. Valid values are &#x60;true&#x60; or &#x60;false&#x60;. Default: &#x60;false&#x60;.
     * @param finished Whether to include the number of finished activity instances in the result or not. Valid values are &#x60;true&#x60; or &#x60;false&#x60;. Default: &#x60;false&#x60;.
     * @param completeScope Whether to include the number of activity instances which completed a scope in the result or not. Valid values are &#x60;true&#x60; or &#x60;false&#x60;. Default: &#x60;false&#x60;.
     * @param incidents Whether to include the number of incidents. Valid values are &#x60;true&#x60; or &#x60;false&#x60;. Default: &#x60;false&#x60;.
     * @param startedBefore Restrict to process instances that were started before the given date. By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/),  the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;,  e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
     * @param startedAfter Restrict to process instances that were started after the given date. By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/),  the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;,  e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
     * @param finishedBefore Restrict to process instances that were finished before the given date. By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/),  the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;,  e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
     * @param finishedAfter Restrict to process instances that were finished after the given date. By [default](https://docs.camunda.org/manual/7.16/reference/rest/overview/date-format/),  the date must have the format &#x60;yyyy-MM-dd\&#39;T\&#39;HH:mm:ss.SSSZ&#x60;,  e.g., &#x60;2013-01-23T14:42:45.000+0200&#x60;.
     * @param processInstanceIdIn Restrict to process instances with the given IDs. The IDs must be provided as a comma- separated list.
     * @param sortBy Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter.
     * @param sortOrder Sort the results in a given order. Values may be asc for ascending order or desc for descending order. Must be used in conjunction with the sortBy parameter.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getHistoricActivityStatistics(id: string, canceled?: boolean, finished?: boolean, completeScope?: boolean, incidents?: boolean, startedBefore?: string, startedAfter?: string, finishedBefore?: string, finishedAfter?: string, processInstanceIdIn?: string, sortBy?: 'activityId', sortOrder?: 'asc' | 'desc', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<Array<HistoricActivityStatisticsDto>>;
    public getHistoricActivityStatistics(id: string, canceled?: boolean, finished?: boolean, completeScope?: boolean, incidents?: boolean, startedBefore?: string, startedAfter?: string, finishedBefore?: string, finishedAfter?: string, processInstanceIdIn?: string, sortBy?: 'activityId', sortOrder?: 'asc' | 'desc', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpResponse<Array<HistoricActivityStatisticsDto>>>;
    public getHistoricActivityStatistics(id: string, canceled?: boolean, finished?: boolean, completeScope?: boolean, incidents?: boolean, startedBefore?: string, startedAfter?: string, finishedBefore?: string, finishedAfter?: string, processInstanceIdIn?: string, sortBy?: 'activityId', sortOrder?: 'asc' | 'desc', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<HttpEvent<Array<HistoricActivityStatisticsDto>>>;
    public getHistoricActivityStatistics(id: string, canceled?: boolean, finished?: boolean, completeScope?: boolean, incidents?: boolean, startedBefore?: string, startedAfter?: string, finishedBefore?: string, finishedAfter?: string, processInstanceIdIn?: string, sortBy?: 'activityId', sortOrder?: 'asc' | 'desc', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext}): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getHistoricActivityStatistics.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (canceled !== undefined && canceled !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>canceled, 'canceled');
        }
        if (finished !== undefined && finished !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>finished, 'finished');
        }
        if (completeScope !== undefined && completeScope !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>completeScope, 'completeScope');
        }
        if (incidents !== undefined && incidents !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>incidents, 'incidents');
        }
        if (startedBefore !== undefined && startedBefore !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>startedBefore, 'startedBefore');
        }
        if (startedAfter !== undefined && startedAfter !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>startedAfter, 'startedAfter');
        }
        if (finishedBefore !== undefined && finishedBefore !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>finishedBefore, 'finishedBefore');
        }
        if (finishedAfter !== undefined && finishedAfter !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>finishedAfter, 'finishedAfter');
        }
        if (processInstanceIdIn !== undefined && processInstanceIdIn !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>processInstanceIdIn, 'processInstanceIdIn');
        }
        if (sortBy !== undefined && sortBy !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>sortBy, 'sortBy');
        }
        if (sortOrder !== undefined && sortOrder !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>sortOrder, 'sortOrder');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'application/json'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        return this.httpClient.get<Array<HistoricActivityStatisticsDto>>(`${this.configuration.basePath}/history/process-definition/${encodeURIComponent(String(id))}/statistics`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
