//
//   Copyright 2026 Deutsches Zentrum für Luft- und Raumfahrt e.V.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//

/**
 * Camunda Platform REST API
 * OpenApi Spec for Camunda Platform REST API.
 *
 * The version of the OpenAPI document: 7.16.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent, HttpParameterCodec, HttpContext } from '@angular/common/http';
import { CustomHttpParameterCodec } from 'src/app/shared/services/camunda-api/encoder';
import { Observable } from 'rxjs';

// @ts-ignore
import { ExceptionDto } from 'src/app/shared/services/camunda-api/model/exceptionDto';
// @ts-ignore
import { MetricsIntervalResultDto } from 'src/app/shared/services/camunda-api/model/metricsIntervalResultDto';
// @ts-ignore
import { MetricsResultDto } from 'src/app/shared/services/camunda-api/model/metricsResultDto';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from 'src/app/shared/services/camunda-api/variables';
import { Configuration } from 'src/app/shared/services/camunda-api/configuration';

@Injectable({
  providedIn: 'root',
})
export class MetricsService {
  protected basePath = 'http://localhost:8080/engine-rest';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();
  public encoder: HttpParameterCodec;

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration
  ) {
    if (configuration) {
      this.configuration = configuration;
    }
    if (typeof this.configuration.basePath !== 'string') {
      this.configuration.basePath = basePath;
    }
    this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
  }

  private addToHttpParams(
    httpParams: HttpParams,
    value: any,
    key?: string
  ): HttpParams {
    if (typeof value === 'object' && value instanceof Date === false) {
      httpParams = this.addToHttpParamsRecursive(httpParams, value);
    } else {
      httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
    }
    return httpParams;
  }

  private addToHttpParamsRecursive(
    httpParams: HttpParams,
    value?: any,
    key?: string
  ): HttpParams {
    if (value == null) {
      return httpParams;
    }

    if (typeof value === 'object') {
      if (Array.isArray(value)) {
        (value as any[]).forEach(
          (elem) =>
            (httpParams = this.addToHttpParamsRecursive(httpParams, elem, key))
        );
      } else if (value instanceof Date) {
        if (key != null) {
          httpParams = httpParams.append(
            key,
            (value as Date).toISOString().substr(0, 10)
          );
        } else {
          throw Error('key may not be null if value is Date');
        }
      } else {
        Object.keys(value).forEach(
          (k) =>
            (httpParams = this.addToHttpParamsRecursive(
              httpParams,
              value[k],
              key != null ? `${key}.${k}` : k
            ))
        );
      }
    } else if (key != null) {
      httpParams = httpParams.append(key, value);
    } else {
      throw Error('key may not be null if value is not object or array');
    }
    return httpParams;
  }

  /**
   * Delete Task Worker Metrics
   * Deletes all task worker metrics prior to the given date or all if no date is provided.
   * @param date The date prior to which all task worker metrics should be deleted.
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public deleteTaskMetrics(
    date?: string,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<any>;
  public deleteTaskMetrics(
    date?: string,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpResponse<any>>;
  public deleteTaskMetrics(
    date?: string,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpEvent<any>>;
  public deleteTaskMetrics(
    date?: string,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<any> {
    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    if (date !== undefined && date !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>date,
        'date'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    let localVarHttpHeaderAcceptSelected: string | undefined =
      options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected =
        this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Accept',
        localVarHttpHeaderAcceptSelected
      );
    }

    let localVarHttpContext: HttpContext | undefined =
      options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (
        this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
      ) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    return this.httpClient.delete<any>(
      `${this.configuration.basePath}/metrics/task-worker`,

      {
        context: localVarHttpContext,
        params: localVarQueryParameters,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Get Sum
   * Retrieves the &#x60;sum&#x60; (count) for a given metric.
   * @param metricsName The name of the metric.
   * @param startDate The start date (inclusive).
   * @param endDate The end date (exclusive).
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getMetrics(
    metricsName:
      | 'activity-instance-start'
      | 'activity-instance-end'
      | 'job-acquisition-attempt'
      | 'job-acquired-success'
      | 'job-acquired-failure'
      | 'job-execution-rejected'
      | 'job-successful'
      | 'job-failed'
      | 'job-locked-exclusive'
      | 'executed-decision-elements'
      | 'history-cleanup-removed-process-instances'
      | 'history-cleanup-removed-case-instances'
      | 'history-cleanup-removed-decision-instances'
      | 'history-cleanup-removed-batch-operations'
      | 'history-cleanup-removed-task-metrics'
      | 'unique-task-workers',
    startDate?: string,
    endDate?: string,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<MetricsResultDto>;
  public getMetrics(
    metricsName:
      | 'activity-instance-start'
      | 'activity-instance-end'
      | 'job-acquisition-attempt'
      | 'job-acquired-success'
      | 'job-acquired-failure'
      | 'job-execution-rejected'
      | 'job-successful'
      | 'job-failed'
      | 'job-locked-exclusive'
      | 'executed-decision-elements'
      | 'history-cleanup-removed-process-instances'
      | 'history-cleanup-removed-case-instances'
      | 'history-cleanup-removed-decision-instances'
      | 'history-cleanup-removed-batch-operations'
      | 'history-cleanup-removed-task-metrics'
      | 'unique-task-workers',
    startDate?: string,
    endDate?: string,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpResponse<MetricsResultDto>>;
  public getMetrics(
    metricsName:
      | 'activity-instance-start'
      | 'activity-instance-end'
      | 'job-acquisition-attempt'
      | 'job-acquired-success'
      | 'job-acquired-failure'
      | 'job-execution-rejected'
      | 'job-successful'
      | 'job-failed'
      | 'job-locked-exclusive'
      | 'executed-decision-elements'
      | 'history-cleanup-removed-process-instances'
      | 'history-cleanup-removed-case-instances'
      | 'history-cleanup-removed-decision-instances'
      | 'history-cleanup-removed-batch-operations'
      | 'history-cleanup-removed-task-metrics'
      | 'unique-task-workers',
    startDate?: string,
    endDate?: string,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpEvent<MetricsResultDto>>;
  public getMetrics(
    metricsName:
      | 'activity-instance-start'
      | 'activity-instance-end'
      | 'job-acquisition-attempt'
      | 'job-acquired-success'
      | 'job-acquired-failure'
      | 'job-execution-rejected'
      | 'job-successful'
      | 'job-failed'
      | 'job-locked-exclusive'
      | 'executed-decision-elements'
      | 'history-cleanup-removed-process-instances'
      | 'history-cleanup-removed-case-instances'
      | 'history-cleanup-removed-decision-instances'
      | 'history-cleanup-removed-batch-operations'
      | 'history-cleanup-removed-task-metrics'
      | 'unique-task-workers',
    startDate?: string,
    endDate?: string,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<any> {
    if (metricsName === null || metricsName === undefined) {
      throw new Error(
        'Required parameter metricsName was null or undefined when calling getMetrics.'
      );
    }

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    if (startDate !== undefined && startDate !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>startDate,
        'startDate'
      );
    }
    if (endDate !== undefined && endDate !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>endDate,
        'endDate'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    let localVarHttpHeaderAcceptSelected: string | undefined =
      options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected =
        this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Accept',
        localVarHttpHeaderAcceptSelected
      );
    }

    let localVarHttpContext: HttpContext | undefined =
      options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (
        this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
      ) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    return this.httpClient.get<MetricsResultDto>(
      `${this.configuration.basePath}/metrics/${encodeURIComponent(
        String(metricsName)
      )}/sum`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Get Metrics in Interval
   * Retrieves a list of metrics, aggregated for a given interval.
   * @param name The name of the metric.
   * @param reporter The name of the reporter (host), on which the metrics was logged. This will have value provided by the [hostname configuration property](https://docs.camunda.org/manual/7.16/reference/deployment-descriptors/tags/process-engine/#hostname).
   * @param startDate The start date (inclusive).
   * @param endDate The end date (exclusive).
   * @param firstResult Pagination of results. Specifies the index of the first result to return.
   * @param maxResults Pagination of results. Specifies the maximum number of results to return. Will return less results if there are no more results left.
   * @param interval The interval for which the metrics should be aggregated. Time unit is seconds. Default: The interval is set to 15 minutes (900 seconds).
   * @param aggregateByReporter Aggregate metrics by reporter.
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public interval(
    name?:
      | 'activity-instance-start'
      | 'activity-instance-end'
      | 'job-acquisition-attempt'
      | 'job-acquired-success'
      | 'job-acquired-failure'
      | 'job-execution-rejected'
      | 'job-successful'
      | 'job-failed'
      | 'job-locked-exclusive'
      | 'executed-decision-elements'
      | 'history-cleanup-removed-process-instances'
      | 'history-cleanup-removed-case-instances'
      | 'history-cleanup-removed-decision-instances'
      | 'history-cleanup-removed-batch-operations'
      | 'history-cleanup-removed-task-metrics',
    reporter?: string,
    startDate?: string,
    endDate?: string,
    firstResult?: number,
    maxResults?: number,
    interval?: string,
    aggregateByReporter?: string,
    observe?: 'body',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<Array<MetricsIntervalResultDto>>;
  public interval(
    name?:
      | 'activity-instance-start'
      | 'activity-instance-end'
      | 'job-acquisition-attempt'
      | 'job-acquired-success'
      | 'job-acquired-failure'
      | 'job-execution-rejected'
      | 'job-successful'
      | 'job-failed'
      | 'job-locked-exclusive'
      | 'executed-decision-elements'
      | 'history-cleanup-removed-process-instances'
      | 'history-cleanup-removed-case-instances'
      | 'history-cleanup-removed-decision-instances'
      | 'history-cleanup-removed-batch-operations'
      | 'history-cleanup-removed-task-metrics',
    reporter?: string,
    startDate?: string,
    endDate?: string,
    firstResult?: number,
    maxResults?: number,
    interval?: string,
    aggregateByReporter?: string,
    observe?: 'response',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpResponse<Array<MetricsIntervalResultDto>>>;
  public interval(
    name?:
      | 'activity-instance-start'
      | 'activity-instance-end'
      | 'job-acquisition-attempt'
      | 'job-acquired-success'
      | 'job-acquired-failure'
      | 'job-execution-rejected'
      | 'job-successful'
      | 'job-failed'
      | 'job-locked-exclusive'
      | 'executed-decision-elements'
      | 'history-cleanup-removed-process-instances'
      | 'history-cleanup-removed-case-instances'
      | 'history-cleanup-removed-decision-instances'
      | 'history-cleanup-removed-batch-operations'
      | 'history-cleanup-removed-task-metrics',
    reporter?: string,
    startDate?: string,
    endDate?: string,
    firstResult?: number,
    maxResults?: number,
    interval?: string,
    aggregateByReporter?: string,
    observe?: 'events',
    reportProgress?: boolean,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<HttpEvent<Array<MetricsIntervalResultDto>>>;
  public interval(
    name?:
      | 'activity-instance-start'
      | 'activity-instance-end'
      | 'job-acquisition-attempt'
      | 'job-acquired-success'
      | 'job-acquired-failure'
      | 'job-execution-rejected'
      | 'job-successful'
      | 'job-failed'
      | 'job-locked-exclusive'
      | 'executed-decision-elements'
      | 'history-cleanup-removed-process-instances'
      | 'history-cleanup-removed-case-instances'
      | 'history-cleanup-removed-decision-instances'
      | 'history-cleanup-removed-batch-operations'
      | 'history-cleanup-removed-task-metrics',
    reporter?: string,
    startDate?: string,
    endDate?: string,
    firstResult?: number,
    maxResults?: number,
    interval?: string,
    aggregateByReporter?: string,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: { httpHeaderAccept?: 'application/json'; context?: HttpContext }
  ): Observable<any> {
    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    if (name !== undefined && name !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>name,
        'name'
      );
    }
    if (reporter !== undefined && reporter !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>reporter,
        'reporter'
      );
    }
    if (startDate !== undefined && startDate !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>startDate,
        'startDate'
      );
    }
    if (endDate !== undefined && endDate !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>endDate,
        'endDate'
      );
    }
    if (firstResult !== undefined && firstResult !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>firstResult,
        'firstResult'
      );
    }
    if (maxResults !== undefined && maxResults !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>maxResults,
        'maxResults'
      );
    }
    if (interval !== undefined && interval !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>interval,
        'interval'
      );
    }
    if (aggregateByReporter !== undefined && aggregateByReporter !== null) {
      localVarQueryParameters = this.addToHttpParams(
        localVarQueryParameters,
        <any>aggregateByReporter,
        'aggregateByReporter'
      );
    }

    let localVarHeaders = this.defaultHeaders;

    let localVarHttpHeaderAcceptSelected: string | undefined =
      options && options.httpHeaderAccept;
    if (localVarHttpHeaderAcceptSelected === undefined) {
      // to determine the Accept header
      const httpHeaderAccepts: string[] = ['application/json'];
      localVarHttpHeaderAcceptSelected =
        this.configuration.selectHeaderAccept(httpHeaderAccepts);
    }
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set(
        'Accept',
        localVarHttpHeaderAcceptSelected
      );
    }

    let localVarHttpContext: HttpContext | undefined =
      options && options.context;
    if (localVarHttpContext === undefined) {
      localVarHttpContext = new HttpContext();
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (
        this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)
      ) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    return this.httpClient.get<Array<MetricsIntervalResultDto>>(
      `${this.configuration.basePath}/metrics`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters,
        responseType: <any>responseType_,
        withCredentials: this.configuration.withCredentials,
        headers: localVarHeaders,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }
}
